"""Spec v4 section 6: the printed Loan Book Report importer becomes build method C, a governed option."""
p = r"C:\Users\wadza\OneDrive\2026\Projects\MAIIC\3. Project Execution\specs\MAIIC_EIR_Engine_Specification_v4_2026-10-07.md"
s = open(p, encoding="utf-8").read()
def rep(old, new):
    global s
    assert old in s, old[:70]
    s = s.replace(old, new)

rep("by one of two methods, both kept and both available at any time: the **bootstrap**, which takes the stored Loan Book Report's latest run for each month as it is, and the **derivation**, which builds the row from the ledger; one command, re-runnable whenever a rule or a source row changes.",
    "by one of three methods, all kept and all available at any time: the **bootstrap**, which takes the stored Loan Book Report's latest run for each month as it is; the **derivation**, which builds the row from the ledger; and the **report importer**, the existing upload of the printed Loan Book Report as an Excel file, which MAIIC has used every month until now; one command, re-runnable whenever a rule or a source row changes.")
rep("### 6.2 The two build methods", "### 6.2 The three build methods")
rep("**Choosing between them.** The method in force is a Governance Centre setting (`loan_book_build_method`, section 4.2) with the two methods as its options,",
    "**Method C, the report importer.** The printed Loan Book Report (Menu ID 3868), uploaded as the Excel file MAIIC produces today, through the importer that already exists (`ProcessLoanImportJob`), unchanged in what it reads. Two things are added so that it lives inside the same design: the parsed rows are landed in `ebanker_loan_book_reports` with the file's hash and load id before `loan_books` is written, so a month loaded this way traces to its file like any other; and the file passes the date gate of 6.4 (every date unambiguous, the row named on failure), because this is the route on which Excel scrambled dates in September. It needs no query and no access to the database, which is its value: a month can be loaded from the report alone when no pack exists, by whoever has the report. It gives the report's figures, like method A, for the months the report was run.\n\n**Choosing between them.** The method in force is a Governance Centre setting (`loan_book_build_method`, section 4.2) with the three methods as its options,")
rep("Both methods read the same landing zone and pass the same gates, so switching changes no import, no route and no screen. Dupleix's recommendation is method B, because it covers every month from the take-on on one basis and traces every figure to a posting; method A is the right choice while the derivation is being proven, for a quick reload of a single month, or whenever MAIIC prefers the report's own figures to stand. Whichever is in force, the other remains available on the feed screen for a named month.",
    "All three read from the landing zone and pass its gates, so switching changes no route and no screen. Dupleix's recommendation is method B, because it covers every month from the take-on on one basis and traces every figure to a posting; method A is the right choice while the derivation is being proven, for a quick reload of a single month, or whenever MAIIC prefers the report's own figures to stand; method C is the right choice for a month with no pack, or if the feed is ever interrupted, since it needs nothing but the report. Whichever is in force, the others remain available on the feed screen for a named month.")
rep("| `ebanker_loads` | The packs themselves |", "| `ebanker_loan_book_reports` | The printed Loan Book Report as uploaded (method C) | File hash and row number | One table per upload; the parsed rows exactly as read |\n| `ebanker_loads` | The packs themselves |")
rep("`eir:build-loan-books {from} {to} {--method=bootstrap|derive}`", "`eir:build-loan-books {from} {to} {--method=bootstrap|derive|report}`")
rep("Rebuilding a month already run, by either method, prints every difference first;", "Rebuilding a month already run, by any method, prints every difference first;")
rep("are not touched by either method.", "are not touched by any of the three methods.")
rep("and the Build action (method A or B, a month or a range) with its approval.", "and the Build action (method A, B or C, a month or a range; method C takes the report file) with its approval.")
rep("| How the loan book is built (`loan_book_build_method`) | Method B, derived from the ledger | Decided D22: both methods of section 6.2 are built; MAIIC switches at any time; the method used is recorded on every row | O8 |",
    "| How the loan book is built (`loan_book_build_method`) | Method B, derived from the ledger | Decided D22: all three methods of section 6.2 are built (bootstrap of the stored run, derivation from the ledger, the printed report importer); MAIIC switches at any time; the method used is recorded on every row | O8 |")
rep("one re-runnable build by either of two methods, the bootstrap of the stored report or the derivation from the ledger, chosen at any time. The Excel report importer becomes a fallback.",
    "one re-runnable build by any of three methods, the bootstrap of the stored report, the derivation from the ledger, or the printed report importer MAIIC uses today, chosen at any time.")
rep("the landing zone and the second method added the same day at Edward's direction, the bootstrap kept as an option |",
    "the landing zone and the derivation added the same day at Edward's direction, the bootstrap and the report importer kept as options |")
rep("Every route produces the same pack and enters by the same door;", "The printed report is not a route: it enters by method C with no pack, and is the one way in that needs no query. Every route produces the same pack and enters by the same door;")
rep("- **Derivation (method B)**: building it from the ledger and the masters, with E-Banker's own arrears fields.",
    "- **Derivation (method B)**: building it from the ledger and the masters, with E-Banker's own arrears fields.\n- **Report importer (method C)**: building it from the printed Loan Book Report uploaded as Excel, the way MAIIC has loaded every month until now, with the file landed and date-checked.")
rep("route 1 and the feed screen, the build by both methods;", "route 1 and the feed screen, the build by all three methods (the report importer landed and gated);")
open(p, "w", encoding="utf-8").write(s); print("method C added")
