"""Spec v4: the trial balances join the landing zone and the bootstrap."""
p = r"C:\Users\wadza\OneDrive\2026\Projects\MAIIC\3. Project Execution\specs\MAIIC_EIR_Engine_Specification_v4_2026-10-07.md"
s = open(p, encoding="utf-8").read()
def rep(old, new):
    global s
    assert old in s, old[:70]
    s = s.replace(old, new)
rep("| `ebanker_loan_book_reports` | The printed Loan Book Report as uploaded (method C) |",
    "| `ebanker_trial_balances` | The monthly trial balance files as received from Finance (19 to date) and the AFS bridge workbook | File hash and row number | One table per file; every GL line exactly as printed, with its cumulative year-to-date balance. `gl_trial_balance_lines`, the GL side of the reconciliation, is derived from it on build; the year-to-date rule of section 7.7 is applied on read, never stored |\n| `ebanker_loan_book_reports` | The printed Loan Book Report as uploaded (method C) |")
rep("### 7.7 The trial-balance importer (unchanged) and the GL opening balances\n\nThe trial-balance corpus of September stands. `GL_02` is added as a small table of keyed GL opening balances so that the bridge can show the two FInES differences as what they are.",
    "### 7.7 The trial balances: landed with the rest, and the GL opening balances\n\nThe trial balance is the check on everything else, so it enters by the same door as everything else. The 19 monthly files and the AFS bridge workbook are committed under `docs/bootstrap/trial-balances-2025-01-to-2026-07/` and landed as `ebanker_trial_balances` (section 6.3); each later month arrives as one more file in the monthly pack, with its hash in the manifest. `gl_trial_balance_lines`, which the reconciliation reads, is derived from the landed files by the build, and `gl_account_scope` still says what each GL code is. The two rules of the September importer are unchanged: a P&L balance is cumulative year-to-date and is turned into a month on read (January taken whole); a balance-sheet balance is never differenced. `GL_02` is landed as the small table of keyed GL opening balances so that the bridge shows the two FInES differences as what they are. The ties the trial balance gives (section 9: the loan GLs to the cent, the FInES differences, interest income year-to-date on 83 of 83) are run by `eir:bootstrap --verify` like every other baseline.")
rep("The committed inputs.** `docs/bootstrap/` in the repository holds, exactly as received and never re-saved: the E-Banker pack of 7 October 2026 (the 18 extracts and the 5 afternoon queries, 23 files), the data-dictionary results of 6 October (24 files), the take-on workbook with its fee columns, the SQL that produced the pack,",
    "The committed inputs.** `docs/bootstrap/` in the repository holds, exactly as received and never re-saved: the E-Banker pack of 7 October 2026 (the 18 extracts and the 5 afternoon queries, 23 files), the data-dictionary results of 6 October (24 files), the 19 monthly trial balances of January 2025 to July 2026 with the AFS bridge workbook for December 2025, the take-on workbook with its fee columns, the SQL that produced the pack,")
rep("| 3 | Lands the committed pack into the landing zone by route 1 (section 6.4): the manifest is checked file by file, the gates run, the accepted exceptions are recorded against the load |",
    "| 3 | Lands the committed pack and the trial balances into the landing zone by route 1 (section 6.4): the manifest is checked file by file, the gates run, the accepted exceptions are recorded against the load |")
# the pack contract: the TB is one more file in the monthly pack
rep("A pack is a set of CSV files, one per query, plus a manifest.", "A pack is a set of files, one per query, plus the month's trial balance from Finance, plus a manifest.")
open(p, "w", encoding="utf-8").write(s); print("TB in landing zone, 7.7 rewritten, bootstrap inputs updated")
