"""Spec v4: what pack 2's first seven files taught (8 Oct, 17:16): GL_03, the first monthly feed, INTEREST_PRODUCT, collateral, guarantors, LOS CLOB."""
p = r"C:\Users\wadza\OneDrive\2026\Projects\MAIIC\3. Project Execution\specs\MAIIC_EIR_Engine_Specification_v4_2026-10-07.md"
s = open(p, encoding="utf-8").read()
def rep(old, new):
    global s
    assert old in s, old[:70]
    s = s.replace(old, new)

# 1. Timeline row
rep("| 7 Oct 2026 | The 18 extracts audited in full.",
    "| 8 Oct 2026 | Pack 2 specified (the September month-end feed, the interest arithmetic, collateral, guarantors, the origination payloads, GL_03, the Mega Farm schemes); seven of its eleven runs received the same evening and checked: the first monthly feed ties on every account, GL_03 settles the year-end adjustments, the collateral register is in hand. |\n| 7 Oct 2026 | The 18 extracts audited in full.")

# 2. Section 2.1 table rows
rep("| Fees | Not available (the largest gap in version 3) | `P2_07` the disbursement charges table: 3,651 rows, 52 in scope, with the income GL of each fee | Covers loans disbursed through E-Banker. Fees on the 109 take-on loans are not in any table and come from Tamanda's template (agreed O14). |",
    "| Fees | Not available (the largest gap in version 3) | `P2_07` the disbursement charges table: 3,651 rows, 52 in scope, with the income GL of each fee; and, once re-run, `P2_13` the origination system's sanction and disbursement payloads | Covers loans disbursed through E-Banker. Fees on the 109 take-on loans are not in any table and come from Tamanda's template (agreed O14). The first `P2_13` export carried the payload as the literal text CLOB; the re-run renders it as text. |\n| Collateral and guarantors | Not available | `P2_11` the customer security register (118 distinct securities, MWK 47.1 billion, on 86 accounts) and `P2_12` the guarantors (71 accounts) | The security register repeats a security across a customer's accounts, so it is de-duplicated on its own id before any coverage is computed. 58 of the 89 active accounts have a security on file; the 31 that do not are a list for Credit before the loss-given-default is built on it. |")
rep("| GL control | The trial balance | The trial balance, every month, plus `GL_02` the keyed GL opening balances | Interest income on a year-to-date basis ties on 83 of 83 comparable account-months. |",
    "| GL control | The trial balance | The trial balance, every month, plus `GL_02` the keyed GL opening balances and `GL_03` the GL legs of the year-end batches | Interest income on a year-to-date basis ties on 83 of 83 comparable account-months, and December 2025 to the cent once the year-end adjustments are read correctly (section 3.4). |\n| The monthly feed | Not tested | `M09_01`, `M09_02` of 8 October: the ledger since the last loaded id with August re-pulled, and the month-end balances for August and September 2026 | The first run of the feed contract of section 6.4: August identical to the 7 October file with no back-dated posting; September's 118 postings on 83 accounts; the balance change equals the ledger on 105 of 105 accounts. |")

# 3. Section 2.2 INTEREST_SUMMARY / INTEREST_PRODUCT
rep("`INTEREST_SUMMARY` (`P1_05`) looked like the calculation behind every interest posting. It is a working table that the month-end run rebuilds; it holds the latest month only (82 rows, all August 2026), confirmed by a second run on 7 October. The history of how each posting was worked out comes instead from the posting's own narration, which states the period and the rate (section 3.1), and from the daily accrual where it exists.",
    "`INTEREST_SUMMARY` (`P1_05`) looked like the calculation behind every interest posting. It is a working table that the month-end run rebuilds; it holds the latest month only (82 rows, all August 2026), confirmed by a second run on 7 October. `INTEREST_PRODUCT` (`P1_05b`, 8 October) does keep history, October 2024 to September 2026 on 126 accounts, and its monthly totals equal the ledger's interest postings on 1,763 of 1,818 shared account-months; but its columns are not what their names say: the \"product\" column holds the computed interest, not the balance times days, and the days column is zero. It confirms the postings and gives a month's interest before the ledger is pulled; the arithmetic behind each posting still comes from the posting's own narration, which states the period and the rate (section 3.1), and from the daily accrual where it exists.")

# 4. Section 3.4 corrected
rep("On 31 December 2025 E-Banker posted 28 \"Diff Int Credit by ROI\" entries (type 120): 22 debits totalling MWK 96,390,096.16 and 6 credits totalling MWK 85,166,683.31. They are the system's own true-up of the year's interest to the rate on the account at year end, and the 6 credits are exactly the difference between Extracts B and C that version 3 could not explain. The engine treats them as interest of December 2025, shows them as their own line in the reconciliation, and the questions for Finance about them are in the note of 7 October (`Note to Barry - the 28 interest adjustments of 31 Dec 2025`).",
    "On 31 December 2025 E-Banker re-rated the year's interest on the PLR-linked book to the rate on each account at year end and posted the difference: 22 debits (type 303) totalling MWK 96,390,096.16 charged to customers and 6 credits (type 120) totalling MWK 85,166,683.31 in their favour, on 1050101 and 1050102 only, in the same interest-posting batches as December's ordinary interest (INTP 41 and 42). The 6 credits are exactly the difference between Extracts B and C that version 3 could not explain.\n\n`GL_03` of 8 October shows the other side: **one net voucher per batch to interest income**. Batch 41 credits 4215 by 32,956,675.55 (the 1050101 debits of 35,940,279.17 less credits of 2,983,603.62); batch 42 debits 4216 by 21,733,262.70 (the 1050102 credits of 82,183,079.69 less debits of 60,449,816.99). All 28 adjustments therefore went through 2025 interest income, net 11,223,412.85, and with that reading the December movement on both income GLs equals the ledger to the cent (1050101: ordinary interest 27,129,967.64 plus 32,956,675.55 equals the trial balance's 60,086,643.19; 1050102: 173,635,459.72 less 21,733,262.70 equals 151,902,197.02). An earlier reading that the debits had not reached income was a double count, since the debits are type 303 and sat inside the ordinary figure; it is withdrawn.\n\nThe engine treats the 28 as interest of December 2025 and shows them as their own line in the reconciliation. The remaining question for Finance is one of intent, not of posting: whether the year-end re-rating to the closing rate was meant to be the policy, since the engine's contractual interest follows the month-end rate month by month (section 3.1) and the two differ by exactly these amounts.")

# 5. 6.7 the first monthly feed proven
rep("5. **Production**, then the same every month by route 1 until route 2 is installed.",
    "5. **Production**, then the same every month by route 1 until route 2 is installed. The first monthly pack, for September 2026, was run on 8 October and behaved as the contract requires: the August re-pull was identical to the first load (no back-dated posting), September arrived complete, and the month-end balances agreed with the ledger on every account.")

# 6. Section 5: Barry row and Finance row
rep("| Barry / vendor | The meaning of status code H; the Zaithwa Farms balance rows rebuilt; the restructured-loan register and the Reschedule Report | The notes of 7 Oct; version 3 phase P7 | Which accounts are live; restructures are version-1 scope |",
    "| Barry / vendor | The meaning of status code H; the Zaithwa Farms balance rows rebuilt; the restructured-loan register and the Reschedule Report; the rest of pack 2 (the 30 September loan-book run, the eight Mega Farm files) and the `P2_13` re-run with the payload rendered as text (`DBMS_LOB.SUBSTR`) | The notes of 7 Oct; pack 2 of 8 Oct; version 3 phase P7 | Which accounts are live; restructures are version-1 scope; the Mega Farm data; the fees and rates at approval |")
rep("| Finance | The questions on the 28 year-end adjustments; the historic materiality threshold;",
    "| Finance | Whether the year-end re-rating of 31 December 2025 was intended as policy (the posting itself is now fully explained, section 3.4); the historic materiality threshold;")
rep("| Credit | The twelve offer letters: the ten samples and the two over-sanction accounts (Mchinji 50m against 100m drawn; VNC Bricks 20m against 200m) | `Request to Credit - the twelve offer letters - 7 Oct 2026.pdf` | Test evidence under D20; the two sanction checks are a control finding |",
    "| Credit | The twelve offer letters: the ten samples and the two over-sanction accounts (Mchinji 50m against 100m drawn; VNC Bricks 20m against 200m); the 31 active accounts with no security on the register (`P2_11`) | `Request to Credit - the twelve offer letters - 7 Oct 2026.pdf`; the collateral list of 8 Oct | Test evidence under D20; the two sanction checks are a control finding; the loss-given-default rests on the register |")

# 7. Section 9 baselines
rep("| Year-end adjustments of 31 December 2025 | 28 postings: 22 debits 96,390,096.16; 6 credits 85,166,683.31 |",
    "| Year-end adjustments of 31 December 2025 | 28 postings: 22 debits 96,390,096.16; 6 credits 85,166,683.31; GL legs 4215 +32,956,675.55 and 4216 -21,733,262.70; December income movement on both GLs equal to the ledger to the cent |\n| The monthly feed (September 2026, the first pack) | August re-pull identical to the first load; September balance change equals the ledger on 105 of 105 accounts |\n| Collateral register | 118 distinct securities, MWK 47.1 billion, after de-duplication on the security id; 58 of 89 active accounts covered |")

# 8. glossary
rep("- **Diff Int Credit by ROI**: E-Banker's year-end adjustment of a year's interest to the rate on the account at year end (type 120).",
    "- **Diff Int by ROI**: E-Banker's year-end re-rating of a year's interest to the rate on the account at year end: debits to customers as type 303, credits as type 120, and one net voucher per batch to interest income.")
open(p, "w", encoding="utf-8").write(s); print("spec updated for pack 2's first seven files")
