services:
    laravel:
        container_name: 'tnmmpamba-laravel'
        build:
            context: ./
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www/html:cached
        networks:
            - tnmmpamba
        ports:
            - '9000'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        working_dir: /var/www/html
        command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
        depends_on:
            - mysql
    mysql:
        container_name: 'tnmmpamba-mysql'
        image: 'mysql/mysql-server:8.0'
        platform: linux/amd64
        ports:
            - '${MYSQL_PORT:-3309}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'tnmmpamba-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - tnmmpamba
    nginx:
        container_name: 'tnmmpamba-nginx'
        build:
            context: "./docker/nginx"
        depends_on:
            - laravel
        volumes:
            - ./docker/nginx/ssl/:/etc/nginx/ssl
            - ./:/var/www/html:cached
            - ./public:/var/www/html/public
            - ./docker/logs/nginx/:/var/log/nginx
            - ./docker/nginx/sites/:/etc/nginx/sites-available
        ports:
            - "${NGINX_PORT:-80}:80"
        networks:
            - tnmmpamba
    mailhog:
        container_name: 'tnmmpamba-mailhog'
        image: mailhog/mailhog
        platform: linux/amd64
        ports:
            - '${MAILHOG_SMTP_PORT:-1026}:8025'
            - '${MAILHOG_WEB_PORT:-8026}:1025'
        networks:
            - tnmmpamba

networks:
    tnmmpamba:
        driver: bridge
volumes:
    tnmmpamba-mysql:
        driver: local
