"""IFRS 9 - impairment (spec v4 section 12.2, workbook 2).

Data for tools/compliance/build_audit.py. Statuses are evidence-based (checked 8 October 2026
against the clean install of eir:bootstrap, the staging, the forward-looking chain, the scenario
set and the test suite). Edit a row, then run:  python tools/compliance/build_audit.py ifrs9_impairment
"""
from tools.compliance.audit_workbook import DONE, PART, OUT_, NA, EVID  # noqa: F401

META = {
    "file_stem": "IFRS9_Impairment_Compliance_Audit",
    "short": "IFRS 9 - impairment",
    "title": "IFRS 9 Financial Instruments - impairment (5.5 and B5.5): staging, significant increase in credit risk, 12-month and lifetime expected credit losses, forward-looking information, write-off",
    "basis": "Prepared 8 October 2026 from the build of specification v4: the staged loan books of July 2024 to August 2026 on the clean install, the Governance Centre's staging and forward-looking settings, the forward-looking chain (fli:correlate), the scenario set of 15.8, and the PHPUnit suite. The PD engine (transition matrices) has not run on the clean install, so the ECL figures there are nil; the rows below audit the mechanics and the settings.",
    "source": "IFRS 9 Financial Instruments as issued by the IASB, section 5.5 and B5.5.1 to B5.5.55. The Reserve Bank of Malawi Financial Services (Credit Risk Management for Development Finance Institutions) Directive 2018 (docs/regulatory). Specification: docs/MAIIC_EIR_Engine_Specification_v4_2026-10-07.md sections 3.6, 13, 14, 15, 16.",
    "reviewer": "Dr Thomson Kumwenda (CFO), then Deloitte",
}

GOV = "Governance Centre: /eir-governance"
ECL = "Financial Modelling, ECL Calculation: /expected-credit-loss"
STAGE = "Governance Centre, Staging & SICR Rules: /stageing-rules; Data Foundation, Loan Book"
FLI = "Financial Modelling, Forward-Looking Model: /regression; fli:correlate; fli:method-cards"
SETS = "Governance Centre, Scenario Sets: /scenario-sets"

ROWS = [
 ("5.5 RECOGNITION OF EXPECTED CREDIT LOSSES", "5.5.1", "A loss allowance for expected credit losses", "Recognise a loss allowance for expected credit losses on a financial asset measured at amortised cost.", DONE,
  "TimePhasedEclService computes the allowance per loan as EAD x PD x LGD, discounted at the EIR, for the period; ifrs9:recalculate-ecl runs it per portfolio; the bootstrap runs it for the last period.", "", "Compliant in mechanics; the PD engine must run for a figure.", ECL, "", "Tests\\Feature\\Ecl\\TimePhasedEclServiceTest; Tests\\Feature\\Ecl\\EclDiscountRateServiceTest"),
 ("5.5 RECOGNITION OF EXPECTED CREDIT LOSSES", "5.5.3", "Lifetime ECL on a significant increase in credit risk", "At each reporting date, measure the loss allowance at lifetime ECL if the credit risk has increased significantly since initial recognition.", DONE,
  "StagingService stages every period: Stage 2 from 31 days past due in every class (the directive), the SICR flag from the qualitative groups, and the ECL takes the lifetime window for Stage 2.", "Spec v4 section 3.6, decision D31.", "Compliant.", STAGE, "dpd_basis", "Tests\\Feature\\Eir\\StagingServiceTest"),
 ("5.5 RECOGNITION OF EXPECTED CREDIT LOSSES", "5.5.5", "12-month ECL where credit risk has not increased significantly", "Measure the loss allowance at an amount equal to 12-month ECL where the credit risk has not increased significantly since initial recognition.", DONE,
  "Stage 1 loans take the 12-month PD window in the ECL service; the staging writes the stage every period.", "", "Compliant.", ECL, "", "Tests\\Feature\\Ecl\\TimePhasedEclServiceTest"),
 ("5.5 RECOGNITION OF EXPECTED CREDIT LOSSES", "5.5.9 to 5.5.11", "Determining a significant increase in credit risk; the 30-days-past-due rebuttable presumption", "Assess the change in the risk of default since initial recognition using reasonable and supportable information; there is a rebuttable presumption that credit risk has increased significantly when payments are more than 30 days past due.", DONE,
  "Stage 2 from 31 days past due in every facility class; days counted from the oldest overdue instalment as the directive counts, with the bucket ageing beside it; a rebuttal of the presumption is a governed setting (staging_rebuttal) whose seeded value cites the directive; the LONG_TERM rule proposing 91 days is seeded future-dated and inactive pending CFO sign-off.", "The O13 rebuttal paper of 8 October.", "Compliant; the presumption is applied, the rebuttal is governed.", STAGE + "; " + GOV, "staging_rebuttal; dpd_basis", "Tests\\Feature\\Eir\\StagingThresholdSeederTest; Tests\\Feature\\Eir\\StagingServiceTest"),
 ("5.5 RECOGNITION OF EXPECTED CREDIT LOSSES", "B5.5.37", "Definition of default; the 90-days-past-due rebuttable presumption", "Apply a definition of default consistent with the one used for internal credit risk management; there is a rebuttable presumption that default occurs no later than 90 days past due unless reasonable and supportable information supports a more lagging criterion.", DONE,
  "Stage 3 from 91 days for a facility of 12 months or less and for the Mega Farm class, and from 181 days for a medium- or long-term facility, as the RBM directive classifies them; the accounting policy's four-consecutive-missed-instalments trigger lifts a loan to Stage 3 beside the day count. The more lagging criterion rests on the directive, cited on each threshold row.", "Spec v4 section 3.6 compares the policy (90 days), the November 2025 model (181) and the directive (181/91).", "Compliant; the rebuttal is documented on the threshold rows.", STAGE, "dpd_basis; stage3_missed_instalments; staging_rebuttal", "Tests\\Feature\\Eir\\StagingServiceTest::test_the_directive_thresholds_by_tenor_class_and_the_bucket_fallback"),
 ("5.5 MEASUREMENT", "5.5.17", "Measurement of expected credit losses", "ECL is an unbiased, probability-weighted amount determined by evaluating a range of possible outcomes, the time value of money, and reasonable and supportable information about past events, current conditions and forecasts of future economic conditions.", PART,
  "Probability weighting across scenarios is built as the governed weighting method (the ECL under each scenario, weighted; sensitivity stored with the set); discounting is at the EIR; the forward-looking chain produces fits from the macro series. The PD engine has not run on the clean install and no fit is approved by a MAIIC reviewer, so the weighted ECL is not yet produced for a period.", "Spec v4 sections 14, 15.", "Partially done: the mechanics are in place; the PD run and an approved fit are awaited.", ECL + "; " + SETS, "scenario_weighting_method; fli_adjustment_route", "Tests\\Feature\\Scenario\\ScenarioSetServiceTest; Tests\\Feature\\Ecl\\EclDiscountRateServiceTest"),
 ("5.5 MEASUREMENT", "B5.5.41 to B5.5.43", "Probability-weighted outcomes", "The estimate reflects the possibility that a credit loss occurs and the possibility that none occurs; a range of scenarios, at least two, weighted by their probabilities.", DONE,
  "The governed scenario set: three or more scenarios, weights summing to 100, the base at least 40 percent and no single weight above 60, every scenario but the base a shock on the base path; the first set (Base 50, Upside 15, Downside 25, Severe 10) is seeded as a proposal for the CFO, each anchored to a year Malawi has lived through.", "Spec v4 section 15.", "Compliant.", SETS, "scenario_minimum_count; scenario_weight_bounds; scenario_calibration_note", "Tests\\Feature\\Scenario\\ScenarioSetServiceTest"),
 ("5.5 MEASUREMENT", "B5.5.49 to B5.5.54", "Reasonable and supportable information; forward-looking information", "Use information that is reasonably available without undue cost or effort, including forecasts of future economic conditions; where a statistical relationship is used it must be supportable.", DONE,
  "Eleven Malawi macro series from the World Bank with their provenance (source, address, fetched-at, who) and a committed snapshot; the forward-looking chain sweeps every driver against every credit-loss proxy over the lag grid under the guardrail (expected sign, R2 cutoff, p-value, minimum observations) and declines a fit that fails with the reason; the structural-events register (the 2023 devaluation, COVID, the policy-rate cycle, the E-Banker take-on) is read by the diagnostics.", "On the clean install: 209 fits, 39 applied by the guardrail, 170 declined.", "Compliant; an applied fit is a proposal under maker-checker.", FLI + "; Data Foundation, Macro Statistics", "fli_expected_sign_test; fli_r2_cutoff; fli_min_observations; fli_alpha; macro_source_precedence", "Tests\\Feature\\FLI\\FliBridgeServiceTest"),
 ("5.5 MEASUREMENT", "B5.5.52 (transmission)", "How forward-looking information reaches the PD", "The method of adjusting the PD for the forecast must be documented and supportable.", DONE,
  "Five governed transmission methods, each with a card: what it does, the formula, what it implies, its preconditions checked live against the data with the deciding figure, and a worked example on one loan; a method whose preconditions are not met cannot be selected; the scalar is seeded because the history cannot yet support the richer methods.", "Spec v4 section 14.7.", "Compliant.", FLI + " (fli:method-cards; /fli/transmission-methods)", "fli_transmission_method; fli_asset_correlation", "Tests\\Feature\\FLI\\TransmissionMethodCatalogueTest"),
 ("5.5 MEASUREMENT", "B5.5.28 to B5.5.30", "Collective assessment and segmentation", "Where information is not available at the instrument level, assess on a collective basis grouped by shared credit-risk characteristics.", PART,
  "Credit-loss proxies are produced for the book and per product group (NPL ratio, Stage 3 share, 12-month default rate), and the segment-specific scalar is a governed method; the PD transition matrices by grade run from their screen and are not yet in the bootstrap chain.", "", "Partially done.", FLI + "; Financial Modelling, PD Model", "fli_transmission_method", "Tests\\Feature\\FLI\\FliBridgeServiceTest"),
 ("5.5 MEASUREMENT", "B5.5.33 to B5.5.35", "Loss given default and collateral", "The cash shortfalls reflect the cash flows expected from collateral and other credit enhancements that are part of the contractual terms.", EVID,
  "LGD runs from the LGD screens (monthly and cumulative); the security register (P2_11, 185 rows) is landed and 31 active accounts carry no security on it (the request to Credit of 7 October).", "", "Evidence needed: the collateral for the 31 accounts; the valuations.", "Financial Modelling, LGD Model; Data Foundation, Collateral Register", "", ""),
 ("5.5 MEASUREMENT", "5.5.17(b), B5.5.44", "Time value of money", "Discount the expected credit losses at the EIR determined at initial recognition.", DONE,
  "EclDiscountRateService takes the locked EIR of the loan (the contractual rate where none is locked, and says so on the row); the bootstrap solves and locks the EIR before the ECL for this reason.", "", "Compliant.", ECL, "", "Tests\\Feature\\Ecl\\EclDiscountRateServiceTest"),
 ("5.5 WRITE-OFF AND PRESENTATION", "5.4.4, B5.4.9", "Write-off", "Write off the gross carrying amount when there is no reasonable expectation of recovery.", EVID,
  "No write-off has been posted in E-Banker since the take-on (DD_16i returned no rows); the policy is MAIIC's to state.", "", "Evidence needed: the write-off policy.", ECL, "", ""),
 ("THE MEGA FARM PROGRAMME", "16", "The Mega Farm loans in the allowance", "Loans extended under the Government's Mega Farm programme (losses to the fund; MAIIC's 5 percent share) must be in the ECL on a documented basis.", EVID,
  "The system holds a November 2025 Mega Farm loan book of 3,490 loans across six GLs (K54.85 bn), found by the build, staged under the MEGA_FARM class (91 days); the programme's treatment (decision D30: out of the EIR engine, in the ECL module, 5 percent share on net) and the PD method (seeded: the agricultural-sector PD scaled to the programme) are governed settings awaiting the CFO's confirmation.", "Spec v4 section 16; the O22 paper of 8 October.", "Evidence needed: the CFO's confirmation of D30; how the K39.76 bn provision of 2025 was arrived at; the monthly Mega Farm books.", GOV + "; Data Foundation, Loan Book (2025-11)", "mega_farms_scope; megafarm_pd_method; megafarm_scalar_ceiling", ""),
]

FINDINGS = [
 ("F1", "5.5.17", "The PD engine has not run on the clean install", "The transition-matrix PD runs from its screen and is not yet callable by the bootstrap; every PD is null and the ECL of the period is nil.", "No weighted ECL for a period; the scenario sensitivity reports zero loans with a PD.", "Lift the transition-matrix logic into a service the bootstrap calls (engine step 4), then run the ECL under the approved scenario set.", "Dupleix", "Open"),
 ("F2", "B5.5.49", "No fit is approved by a MAIIC reviewer", "The chain applied 39 fits by the guardrail; approval of a fit for use in the FLI route is a maker-checker decision not yet taken.", "The forward-looking adjustment is the manual overlay at zero until then.", "A reviewer approves a fit on the FLI Adjustments screen; a second person reviews.", "Dr Thom / the reviewer", "Open"),
 ("F3", "16", "The Mega Farm provision basis is undocumented in the system", "The 2025 statements carry K39.76 bn against K48.7 bn Stage 3; the November 2025 book in the system is mostly Stage 1 by days past due.", "The ECL golden number at 31 December 2025 cannot be set.", "The CFO confirms D30 and the provisioning method; the monthly Mega Farm books are loaded by the feed (MF_01 to MF_08).", "Dr Thom / Barry", "Open"),
]

BASELINES = []
