"""Notice 1198 of 2025 - Internal Capital Adequacy Assessment Process (ICAAP) Directives.

Data for tools/compliance/build_audit.py. Statuses are evidence-based (checked 29 Sep 2026
against reporting context #11, BoZ ICAAP return #1, Report Centre pack #1, the bound engine
runs #11, capital projection run #1, the Pillar 2 register and the report profile). Edit a
row, then run:  python tools/compliance/build_audit.py notice_1198_icaap
"""
from tools.compliance.audit_workbook import DONE, PART, OUT_, NA, EVID  # noqa: F401

META = {
    "file_stem": "BoZ_Notice_1198_ICAAP_Compliance_Audit",
    "short": "Notice 1198 of 2025 - ICAAP Directives",
    "title": "BoZ Gazette Notice No. 1198 of 2025 - The Banking and Financial Services (Internal Capital Adequacy Assessment Process) Directives, 2025",
    "basis": "Prepared 29 September 2026 from the tool's outputs for reporting context #11 (2025-Q4): BoZ ICAAP return #1 (icaap_regulatory_reports), ICAAP Report Centre pack #1, engine runs #11, capital projection run #1, the Pillar 2 register (pillar2_risk_assessments) and the report profile. All approvals in this database are UAT stand-ins written by UatBozReturnBlockersApprovalSeeder ('not a real sign-off'); the Board has not approved anything in the system.",
    "source": "Zambia Gazette Vol. LXI No. 116, 19 Sep 2025, pp. 968-978 (Gazette Notice No. 1198 of 2025, Rule 20 of the Capital Adequacy Rules 2025, dated 10 Sep 2025). Repo: docs/regulatory/Capital Rules/Special_Gazette_116_BoZ_Capital_Rules_Directives.pdf, pdf pages 14-24. Schedule I is on gazette pages 974-977 (pdf 20-23); the Appendix I template on pages 977-978 (pdf 23-24). The gazette prints s.16(1) paragraphs (a) and (c)-(f): there is no (b).",
}

CTX = "Reporting context #11 (2025-Q4, approval_state approved by 'Chief Risk Officer (UAT)', snapshot frozen 28 Sep 2026): /reporting-contexts/11"
RET = "BoZ ICAAP return #1: /reports/icaap-regulatory (exports /reports/icaap-regulatory/1/excel, /pdf, /word)"
PACK = "ICAAP Report Centre pack #1: /reports/icaap-report-centre/1 (exports /pdf, /word, /excel)"
P2 = "Pillar 2 register (pillar2_risk_assessments #1-#6): /pillar2-risk-assessments; BoZ Return sheet 'Pillar 2 Assessments'"
PROFILE = "Report profile /reports/profile (setting icaap_report_profile is not saved, so the pack prints the code defaults in ReportProfileController::defaults())"
UAT = "UAT stand-in only: approvals written by UatBozReturnBlockersApprovalSeeder (CRO 'UAT', signature 'UAT-PLACEHOLDER'); printed documents blank them for hand signature (app/Support/PrintedDocument.php)"

# (Part, ref, name, action, status, tool comment, general comment, app compliance comment, app reports reference)
ROWS = [
 ("PART I", "1", "Short Title", "Cite as the Banking and Financial Services (Internal Capital Adequacy Assessment Process) Directives 2025 (Gazette Notice No. 1198 of 2025, Rule 20).", DONE,
  "The return cites 'BoZ ICAAP Directives 2025' on its Cover and Ownership & Approval sheets and 'Rule 20' against s.6 (basis), s.9 (independent review) and s.10(3) (remediation plan) in IcaapRegulatoryReportService.", "In force from 19 Sep 2025; applies to the Dec-2025 ICAAP.", "Compliant.", RET + " - sheets 'Cover', 'Ownership & Approval'"),
 ("PART I", "2", "Interpretation", "Apply the defined terms: market risk, risk appetite (aggregate level and types of risk, decided in advance, within risk-taking capacity), scenario analysis (historical or hypothetical circumstances), stress testing (forward-looking tool for adverse events).", DONE,
  "Used with the directive's meaning: the RAS sets targets/triggers in advance (risk_appetite_statements, 26 metrics); the scenario library holds historical and hypothetical scenarios; stress runs are forward-looking and carried through ECL, RWA, capital and liquidity.", "No divergence of definitions found.", "Compliant.", "/risk-appetite; /stress; Report Centre pack Glossary"),
 ("PART I", "3", "Application", "Applies to banks, and to financial institutions (ZNBS is a building society) 'where the Bank requests'.", EVID,
  "The tool applies the directive in full. Whether BoZ has requested ZNBS (a deposit-taking financial institution) to apply Notice 1198 is not recorded. docs/regulatory/Capital Rules/README.md notes that deposit-taking FIs comply with Rules 12/20/21 only where BoZ so determines.", "ZNBS filed an ICAAP at 31 Mar 2025 (the prior comparator in the pack), which suggests BoZ expects one; the request letter should be on file.", "Compliant either way; applicability evidence to be filed (Findings F3).", RET),
 ("PART II", "4", "Overview of the ICAAP", "(1) Put in place an ICAAP for overall capital adequacy against the risk profile and a strategy for maintaining capital; (2) capital management integral to risk management, aligned to strategy, risk appetite, risk profile and loss-absorbing capacity; (3) ICAAP integral to management and decision-making and embedded in business and organisational structures; (4) Board responsible for level and quality of capital commensurate with the risk profile, including future changes.", EVID,
  "(1)-(2) are implemented: the capital assessment (CapitalAdequacyAssessmentService) relates Pillar 1 K340,301k, buffers K102,090k and Pillar 2 K17,032k to capital K1,348,811k, and the capital plan projects 2026-2028. (3) and (4) are claims the tool prints ('The use test is satisfied', pack s.2.3; 'The Board concludes', return Executive Summary) but cannot evidence: no Board minute, ALCO pack or decision record is held.", "Embedment and Board ownership are ZNBS facts, not system outputs.", "Tool-side compliant; embedment and Board evidence outstanding (Findings F1).", RET + " - 'Executive Summary', 'Capital Adequacy Assessment'; Report Centre pack s.2.3 'Use of the ICAAP'"),
 ("PART II", "5", "Obligations under the ICAAP", "(a) regular assessment of the amount, type and distribution of capital; (b) identify major sources of risk to meeting liabilities as they fall due; (c) stress and scenario tests against severe but plausible shocks; (d) processes, strategies and systems proportionate to the business; (e) fully document the ICAAP; (f) review and update the ICAAP document at least annually or on major change.", PART,
  "(a) capital run #11 and Appendix I; (b) liquidity run #11 (LCR/NSFR, survival horizon) and the return 'Liquidity & Funding Assessment'; (c) 65 completed stress runs, 30 scenarios in the reporting set, reverse stress; (d) governed engines and parameter sets; (f) the prior ICAAP at 31 Mar 2025 is carried as comparator and the Dec-2025 ICAAP is 9 months later. (e) is only partly met: Schedule I items are missing or come from code defaults (see the SCHEDULE I rows).", "Documentation completeness is the gap, not the mechanics.", "Partially compliant: (e) depends on closing the Schedule I gaps.", RET + "; " + PACK + "; /stress"),
 ("PART III", "6", "ICAAP on a Solo and Consolidated Basis", "Prepare the ICAAP report on a solo and, where applicable, a consolidated basis.", DONE,
  "Cover basis is 'Solo', from the governed setting icaap_reporting_basis (basis_source 'governed_setting'), printed on the return Cover sheet. No group entity or subsidiary is recorded for ZNBS, so no consolidated report is produced.", "ZNBS to confirm it holds no subsidiary (none appears in the data or the pack).", "Compliant (solo); consolidated not applicable while no subsidiary exists.", RET + " - sheet 'Cover' (Basis: Solo)"),
 ("PART III", "7", "Governance Framework", "Board has primary responsibility for adequate capital and shall: (a) set risk appetite and tolerance; (b) establish a capital management policy covering current/future requirements, approved capital targets, capital needs/expenditure/external sources, and contingency measures below internal minimum; (c) maintain supplementary policies incl. stress testing and dividend policies; (d) methods to monitor compliance; (e) require management to set up a risk framework, monitoring system, compliance method and communication of policies.", EVID,
  "The tool holds the artefacts but none is Board-evidenced: RAS 26 metrics status 'approved' with approved_by NULL (seeded); dividend policy ZNBS_DIVIDEND_POLICY (40%) approved by user #1 System Administrator, its own creator; capital contingency triggers, buffer replenishment and the policy register (ICAAP, Capital Management, Stress Testing policies 'Nov 2025') are code defaults in ReportProfileController; Capital Adequacy Plan #1 is 'draft', reviewed_by/approved_by NULL.", "The policies themselves are ZNBS documents; the tool can only reference them.", "Evidence needed: Board-approved RAS, capital management, stress testing and dividend policies (Findings F1, F12, F20).", "/risk-appetite; /governance (dividend policy); /reports/capital-adequacy-plan/1; " + PROFILE),
 ("PART III", "8", "Monitoring and Reporting", "(1) Adequate system for monitoring and reporting risk exposures and how the changing risk profile affects capital needs; (2) regular reporting to the Board so it can evaluate material risks and their capital effect, test key assumptions, confirm capital sufficiency and assess future requirements.", EVID,
  "(1) is implemented: EWS (48 indicators, 7 alerts, score #1 bound to context #11), RAS dashboard with live readings (22 green, 1 amber, 2 red, 1 n/a in the pack), Board deck exports. (2) Regular Board reporting cannot be evidenced from the system: no Board pack, minute or reporting calendar is held; the return states only that Risk monitors liquidity limits monthly.", "Frequency of Board risk reporting should be stated and evidenced.", "Tool ready; Board reporting evidence outstanding.", "/ews; /workbooks/ews; /risk-appetite; /dashboard/export/board-pdf; Report Centre pack s.5.0 Figure 4 (RAS dashboard)"),
 ("PART III", "9", "Independent Review of the ICAAP", "(1) Independent review through internal or external audit; (2) assess comprehensiveness, proportionality and coverage of major risks; (3) periodic review of the risk management framework; (4) review areas (a)-(h): process, material risks incl. large exposures and concentrations, methodology and data, scenarios, stress assumptions, integration with risk management, capital planning and targets, MIS.", PART,
  "Mechanics exist: the return carries a structured independent-review block (reviewer, role, date, opinion; Rule 20 s.9) that prints as a blank form. No review is recorded: return #1 independent_review is NULL, mrm_validations has 0 rows. BUT pack Appendix 4 (_review_of_icaap.blade.php) prints 'Completed' for Internal Audit, Management, Finance & Audit Committee and Board whenever the pack is Board-approved - true here only because of the UAT CRO approval - so the printed pack overstates the review position.", "An independent review is a ZNBS Internal Audit deliverable; the pack must not print it as done before it is.", "Non-compliant in output (Appendix 4 status) and evidence outstanding (Findings F4, F5).", RET + " - sheet 'Ownership & Approval' (Independent Review / Internal Audit Sign-Off); Report Centre pack Appendix 4 'Review of the ICAAP'"),
 ("PART IV", "10", "Sound Capital Assessment", "(1) Policies to identify, measure and report all material risks; a process relating capital to risk; capital adequacy goals; internal controls, reviews and audit. (2) A reasonable estimate of overall capital required. (3) Where capital falls below the ICAAP estimate, a detailed explanation and a plan to raise capital.", DONE,
  "Overall requirement K459,423k (Pillar 1 340,301 + CCB buffer 102,090 + Pillar 2 17,032 + stress line nil = 13.5% of RWA 3,403,007) against capital K1,348,811k: surplus K889,388k. The return computes a conditional remediation plan (remediation.is_required when Appendix I surplus < 0); not triggered. Internal controls/audit of the process fall under s.9.", "Estimate reconciles across the return, pack and Appendix I (Reconciliation sheet).", "Compliant; s.10(1)(d) evidence tracked under s.9.", RET + " - 'Capital Adequacy Assessment', 'Appendix I', 'Reconciliation'; Capital run #11 (/capital/11)"),
 ("PART IV", "11", "Comprehensive Risk Management Policies and Procedures", "Policies and procedures shall: (a) capture credit, market, operational and other risks; (b) have controls to identify and measure all material risks; (c) use reliable techniques on good-quality inputs; (d) allow qualitative judgement for hard-to-quantify risks; (e) promptly reflect risk-profile changes; (f) require stress tests of adverse events on capital.", PART,
  "(a) Pillar 1 credit/market/operational plus 11 Pillar 2 risk types; (d) six judgement assessments with written WHY/REVISIT reasoning in the Pillar 2 register; (e) EWS and RAS monitoring; (f) stress suite. (c) is partial: the data-gap register (docs/final specs/Data_Gap_ZNBS_Data_To_Be_Verified_And_Actions_Taken.md, Part C) lists inputs ZNBS has still to supply or confirm, and the return itself contains 'UAT PLACEHOLDER - to be confirmed by ZNBS' statements. The policy documents are not held in the tool.", "Input quality is the binding constraint.", "Partially compliant: close the data-gap register items (Findings F7).", P2 + "; Data Gap register Part C"),
 ("PART IV", "12", "Proportionality", "Sophistication commensurate with the business. Categorise activities as (a) simple (largest losses of the past 3-5 years, list of material risks, capital per risk, 3-5 year business-plan effect, documented range subject to Board approval), (b) moderately complex (items (i)-(ix): comprehensive risk list, loss distributions and stress testing, coverage, extra capital and mitigants, risk that the analysis is flawed, 3-5 year projections reviewed annually, adverse scenarios over the horizon, Board-approved documentation, back-testing) or (c) complex (models for an overall estimate).", PART,
  "The Society's own categorisation is not recorded anywhere in the tool (the pack only says the ICAAP is 'proportionate'). Most (b) items are produced: material risk list, stress testing, capital coverage, 3-year projection (2026-2028), model-limitation disclosure (return 'Model Risk, Data Quality & BCBS 239'). Gaps: (b)(vii) the per-scenario projection paths do not carry the shock beyond 2025 Q4; (b)(ix) back-testing is only a bridge to the Mar-2025 ICAAP (mrm_backtests 0 rows); (a)(i) largest losses of the past 3-5 years are not presented.", "The categorisation drives which catalogue BoZ will test against.", "Partially compliant (Findings F13, F16).", "/capital/projections/1; " + RET + " - 'Model Risk, Data Quality & BCBS 239'"),
 ("PART IV", "13", "Capital Planning", "(1) Forward-looking ICAAP (strategy, macro factors, stress, future constraints); (2) Board strategy to maintain adequate capital; (3) a Board-approved capital plan and formal process, including (i) capital target, (ii) time horizon, (iii) anticipated capital utilisation, (iv) general contingency plan.", PART,
  "(1) Capital projection run #1 (imported ZNBS CSP forecast, 3 years): base CAR 39.79/45.88/45.50%, stress 32.22/26.44/21.67%, post-action 32.22/30.19/24.33% for 2026-2028. (3) Capital Adequacy Plan #1 is 'draft' (reviewed_by and approved_by NULL; narrative 'seeded on the demo 3-year projection'). The capital target is stated three ways: RAS CAR target 15% / trigger 12%; plan #1 internal band 13-15%; projection run #1 target band 30.96-35.96% ('stress_derived_band'). Contingency triggers are code defaults.", "A single Board-approved target and plan is required.", "Partially compliant (Findings F10, F11).", "/capital/projections/1; /workbooks/capital-projection/1; /reports/capital-adequacy-plan/1; Report Centre pack s.7.0 'Capital Planning'"),
 ("PART IV", "14", "Risk-based Capital Targets", "(1) Capital targets consistent with risk profile and environment; (2) the ICAAP document includes all material risk exposures; (3) it indicates which risks are measured quantitatively or qualitatively.", PART,
  "(2)-(3): Appendix I and the Pillar 2 register cover all Pillar 1 and Pillar 2 lines, each with method (engine vs judgement_pct) and basis. But the pack's material-risk table (code default copied from the Mar-2025 ICAAP Table 18) says Business/Strategic carries a 4% and Reputation a 2% Pillar 2 add-on 'in ICAAP capital', while Appendix I holds both at nil. (1) The target is inconsistent across RAS, plan and projection (see s.13).", "Two tables in the same pack disagree on which risks are capitalised.", "Partially compliant (Findings F9, F11).", RET + " - 'Appendix I', 'Pillar 2 Assessments'; Report Centre pack s.5.0 material risk table"),
 ("PART IV", "15", "Stress Tests and Scenario Analysis", "Periodically run relevant stress tests and scenario analyses for unlikely but plausible events, at a frequency proportionate to the business.", DONE,
  "65 completed stress runs; 30 scenarios in the reporting set across credit, liquidity, market, operational, concentration, climate, ESG, macro and combined families, plus reverse stress. Worst: 'ZNBS O1 K250m Operational Loss Event' (run 30), CAR 32.12%. Liquidity stress: combined scenario and survival horizon in the return. Scenarios are approved by user #1 System Administrator, not by a Board-level body (see Schedule I stress row).", "Frequency is set by the Stress Testing Policy (not held).", "Compliant (mechanics and results).", "/stress; /stress/runs/30; /stress/reverse-stress-results; Report Centre pack s.6.0 and Appendix 5"),
 ("PART IV", "16", "Use of Internal Models", "Where an internal model is used for capital planning: (a) documented specification, methodology and assumptions; (c) independent validation of inputs and outputs; (d) plausibility checks under extreme conditions; (e) a confidence level on outputs; (f) link to business strategy. (2) Show reliance on historical data and back-testing. (3) Skills and resources to run the model. (Gazette omits para (b).)", PART,
  "Pillar 1 uses standardised/BIA approaches; the stress engine and capital projection are the internal models used for capital planning. (a) specs exist in docs/final specs; (d) reverse stress and the extreme scenarios. Gaps: (c) no independent validation (mrm_validations 0 rows; model-risk add-on K2,722k held for it); (e) no confidence level assigned; (2) no back-test records (mrm_backtests 0); the MRM inventory (/mrm, 8 models: OLS, AR(1), Monte Carlo, AI Management Action Advisor, etc.) does not list the capital, IFRS 9, stress transmission, liquidity or IRRBB engines the return says it relies on.", "(3) skills and resources are a ZNBS matter.", "Partially compliant (Findings F14).", "/mrm; " + RET + " - 'Model Risk, Data Quality & BCBS 239'; Appendix I 'Model Risk' K2,722k"),
 ("PART IV", "17", "Challenge and Approval by the Board", "(1) Documented ICAAP outcome challenged and approved by the Board; (2) Board has ultimate responsibility for structure, content and implementation; (3) ICAAP document submitted to BoZ, stating the capital deemed appropriate and the composition of capital.", EVID,
  "(3) content is produced: Appendix I states the overall requirement K459,423k and composition (CET1 1,323,841, AT1 0, Tier 2 24,970). (1)-(2) are not evidenced: return #1 approval is by 'Chief Risk Officer' with designation 'For the Board (UAT placeholder - no Board resolution recorded)'; pack #1 approval by user #4 with reason 'UAT back-end approval ... not a real sign-off'. Return status 'submitted' was set by System Administrator on 28 Sep 2026 with no submission_reference. The draft Board resolution printed in the pack asserts a stress shortfall that the results do not show.", UAT + ".", "Evidence needed: Board minute, signed approval and BoZ submission reference (Findings F1, F2, F6).", RET + " - 'Ownership & Approval', 'Appendix I', 'Submission'; Report Centre pack front matter 'Board Resolution'"),
 ("PART IV", "18", "Format of the ICAAP", "Any appropriate format, provided the Schedule I issues are addressed at a minimum.", PART,
  "The return follows Schedule I order but its Schedule I sheets carry narrative only: IcaapRegulatoryExcelExporter::worksheets() skips the 'ownership_approval' narrative (so the Review, Challenge, Approval and Embedment text never reaches the return), and the tables that answer Schedule I items (board and committees, policy register, RAS metrics, material-risk table, five-year financials, loan-book analysis, contingency plan, dividend policy) exist only in the Report Centre pack. The return's Risk Appetite sheet refers to 'the appendix' for the RAS, which the return does not contain.", "Filing the pack alongside the return would cover most items; the gaps listed in the SCHEDULE I rows remain either way.", "Partially compliant (Findings F8).", RET + "; " + PACK),
 ("PART V", "19", "Bank of Zambia Assessment", "BoZ conducts the supervisory review and evaluation and may impose prudential measures (capital above minimum, provisions, controls, risk reduction, other measures under the Act).", NA,
  "Obligation on BoZ, not ZNBS. The tool can carry a BoZ-directed add-on through governed Appendix I overrides (none recorded: appendix_i_overrides = []) and prints SREP principles in the pack.", "Record any BoZ SREP letter or directed add-on when received.", "Not applicable to ZNBS (obligation on the regulator).", RET + " - 'Appendix I' overrides; Report Centre pack Appendix 3 'SREP Principles'"),

 ("SCHEDULE I", "SchI-1", "Ownership and Approval of the ICAAP", "Evidence of review, challenge and approval: three signature tables (Name, Designation, Signature, Date) - prepared by; reviewed by; challenged and approved by the Board.", EVID,
  "Return 'Ownership & Approval' sheet has the three blocks. prepared_by = 'System Administrator / Preparer (UAT placeholder)'; reviewed_by is empty; board_approved = 'Chief Risk Officer / For the Board (UAT placeholder - no Board resolution recorded)', all with signature 'UAT-PLACEHOLDER' - printed as blank lines for hand signature. The pack sign-off matrix names Director Risk and Director Finance (review), MD and Head Internal Audit (challenge), Board Chair and the two committee chairs (approval) from the profile signatory register.", UAT + ".", "Tool ready; real signatures and dates to be obtained (Findings F1).", RET + " - sheet 'Ownership & Approval'; Report Centre pack front matter 'Ownership and Approval of ICAAP'"),
 ("SCHEDULE I", "SchI-2", "Executive Summary", "Summary covering 13 items: purpose, challenge/approval/embedment; background and subsidiaries; shareholders' funds and willingness to meet future capital needs; developments of the past five years; board and management overview; day-to-day risk management; the RAS; Pillar 1 and 2 capital allocation; non-capital mitigants; liquidity management; stress results pre/post management action; capital needs and sources; challenges and refinements.", PART,
  "The return Executive Summary (from pack s.1.0, 3 paragraphs) covers capital, Pillar 1/2 allocation, buffers, surplus, CAR/CET1/leverage, LCR/NSFR and the binding stress (items 8, 10, 11 in part). Items 2-7, 9, 12 and 13 are not summarised, and it prints 'The Board concludes that the Society holds adequate capital' although no Board conclusion is recorded.", "The pack adds executive capital and position summary tables, but not the missing items.", "Partially compliant (Findings F1, F8).", RET + " - sheet 'Executive Summary'; Report Centre pack s.1.0"),
 ("SCHEDULE I", "SchI-3", "Review, Challenge, Approval and Embedment", "Eight items: purpose and overview; Board's role in challenge and approval; reviews by Board, senior management, external party and internal audit with frequency, findings and follow-up; senior management's role; outsourced components (provider, risks, mitigation); embedment in decisions, planning and risk management; list of documents and policies used; significant changes versus the previous report.", PART,
  "Pack s.2.0 (2.1-2.5) covers items 1, 2, 4, 6 in generic system-generated text, item 7 (documents register, 8 entries, code defaults) and item 8 (Mar-2025 comparator with line explanations). Missing: item 3 (no review, finding or follow-up is recorded - pack 2.5 simply asserts review by Senior Management and Internal Audit); item 5 (outsourcing is not addressed although the ICAAP is prepared on a third-party-built system). The return omits this section's narrative altogether (see s.18).", "Item 3 and item 5 need ZNBS facts.", "Partially compliant (Findings F4, F5, F8, F19).", PACK + " s.2.0 'Approval and Use of ICAAP'; " + RET + " - 'Governance, Review & Embedment' (governance text only)"),
 ("SCHEDULE I", "SchI-4", "Background", "Structure and group; capital composition; parent/ownership and regulator; subsidiaries; business environment; main activities, customers, products; strategic plan with 3-5 year projections; results by business line; five years of financial data with commentary; loan book analysis (a) retail/SME/corporate, (b) sector/large/geographic/insider concentration, (c) internal grading, (d) NPLs and provisions, (e) off-balance sheet, (f) securities incl. maturity and encumbrance; shareholders' funds and willingness; significant developments of five years.", PART,
  "Produced in pack s.3.0: capital composition, CSP projections 2026-2028, macro outlook, segmental split (Unsecured 60.4% / Mortgage 39.6% of loans), IFRS 9 stage table (Stage 3 K120.1m, coverage 79.2%), insider loans K180.3m (7.1%), off-balance K40.4m, securities by maturity. Gaps: only 4 years of actuals (2022-2025) though 2021 actuals are in financial_statements; no retail/SME/corporate, geographic or internal-grade analysis; no encumbrance level; no shareholders' willingness statement; 'Significant developments' is generic and omits the change of year-end (Apr-Dec 2025 nine-month stub; income statement 2025 id 20 months = 9) while the pack is labelled 'FY ended 31 December 2025'. Ownership table (Ministry of Finance majority; Workers Compensation Fund Control Board and NAPSA minority) is a code default, whereas docs/regulatory/Capital Rules/README.md records the audited AFS as 100% GRZ-owned.", "The return's Background sheet is text only.", "Partially compliant (Findings F8, F17, F18).", PACK + " s.3.0 'Background and Business Environment'; " + RET + " - sheet 'Background'"),
 ("SCHEDULE I", "SchI-5", "Governance Structure", "Board composition, experience and number of independent directors; organisation and senior management experience; board and management committees, terms of reference and delegations; key Board-approved policies with review dates; three lines of defence; organisation chart for risk management; evidence of independent review of internal controls, findings and remediation; group functional matrix; who identifies, assesses and manages each key risk.", PART,
  "Pack s.4.0 prints the Board (5 names and roles), ExCo (5), two Board and two management committees with one-line mandates, policy register (7 policies, last/next review), three-lines narrative, organisation chart and the risk-ownership table (11 risks). All are code defaults never saved to icaap_report_profile. Missing: directors' experience and number of independent directors; management experience; terms of reference and delegations; evidence of independent review of internal controls and remediation. Group matrix: not applicable (no group). The risk-ownership table names committees (Credit Committee, Operational Risk and Control Committee) that the committee lists omit.", "Content must come from ZNBS Board Secretary and HR.", "Partially compliant (Findings F18).", PACK + " s.4.0 'Governance Structure'; " + PROFILE),
 ("SCHEDULE I", "SchI-6", "Risk Appetite and Material Risk Assessment", "Formal RAS with overriding appetite, tolerance and review frequency; alignment to strategy; for each material risk: definition and identification, methodology, limits, number of breaches, remedial actions and limit changes; reporting frequency; internal/external review of the risk system; aggregated overall risk position with interdependencies; non-capital mitigants; liquidity (a)-(h): ALCO, policy, delegated authorities, intra-group, commitments, sources and uses, quantified CFP, link to capital planning. Appendix I mandatory.", PART,
  "Produced: RAS 26 metrics with target/trigger and RAG (pack s.5.0 Figure 4, Appendix 2), RAS rationale table, Pillar 2 register with method and reasoning, Appendix I, liquidity section (ALCO, funding profile, sources/uses, commitments K40.4m, link to capital planning). Gaps: RAS review frequency not stated and RAS approved_by NULL; breaches shown point-in-time only (no count over the year, no limit-change history); no review of the risk system; aggregation is a simple sum with no statement on correlations; intra-group and the Contingency Funding Plan are 'UAT PLACEHOLDER - to be confirmed by ZNBS'. The liquidity sheet reports LCR 1,988% / NSFR 151.5% as 'the one reported in this return' while the Executive Summary and liquidity run #11 give 2,640.91% / 131.54%. The material-risk table conflicts with Appendix I (s.14).", "The RAS depositor-concentration limit is itself disputed (40% in RAS vs 25% in ALCO/ICAAP).", "Partially compliant (Findings F7, F9, F20).", RET + " - 'Risk Appetite & Material Risk A', 'Liquidity & Funding Assessment', 'Appendix I'; Report Centre pack s.5.0 and Appendix 2; Liquidity run #11 (/liquidity/11)"),
 ("SCHEDULE I", "SchI-7", "Scenario Analysis and Stress Testing", "Key features of the framework; Board's role in reviewing and approving it and its frequency; material risks covered, with reasons for inclusion/exclusion; scenarios incl. recession, methods, assumptions, results and management actions; capital required pre- and post-management actions for ALL stress tests, in-house and regulatory, and a capital buffer.", PART,
  "Produced: framework and transmission explained (return 'Stress Testing & Scenario Analysis'; pack s.6.0), 30 scenario results with base/stressed/post-action pass-fail (Appendix 5), scenario design table, reverse stress. Gaps: no Board role or review frequency recorded (55 of the 56 scenarios approved by user #1 System Administrator, one with no approver); no reasons for excluding risks; post-management-action capital exists for only 2 scenarios (post-action runs #1 'L1 Retail Deposit Run', #2 'C5 35% NPL'), not the binding one - the return states 'No post-action run bound to the worst stress scenario'; no BoZ-prescribed regulatory stress test is in the library (scenario 41 'BoZ ICAAP Adverse Pack' is an in-house calibration).", "Stress capital line is nil because the worst stressed CAR 32.12% stays above 13%.", "Partially compliant (Findings F15).", RET + " - 'Stress Testing & Scenario Analy', 'Appendix I' (stress evidence); /stress/post-actions/1; Report Centre pack s.6.0 and Appendix 5"),
 ("SCHEDULE I", "SchI-8", "Capital Planning", "Planning approach (frequency, stakeholders, tools); projected requirements on an approved business plan and capital contingency plan: (a) sources/quality/composition of capital, (b) funding of major investments, (c) group needs, (d) expected capital injections with basis, amount and timing, (e) internally generated capital; Board and senior-management review; outcome over the horizon incl. stress; dividend policy; capital buffer and its replenishment in stress.", PART,
  "Produced: base, stress and post-action paths 2026-2028 with CET1/T2/RWA/ratios (pack s.7.0, forecast provenance sheet), contingency triggers, dividend-policy text, buffer-replenishment text, CCB K102,090k. Gaps: (d) projection run #1 holds a K250m CET1 issuance in 2027 (planned_actions; planned_action_amount 250,000 on the baseline and post-action 2027 rows) with no recorded basis or source; (e) dividends paid are 0 in every projected year although the stated earnings basis is 60% retained / 40% distributed; Board/senior-management review not evidenced (Capital Adequacy Plan #1 draft); dividend policy approved by its own creator (user #1).", "Group capital needs: not applicable.", "Partially compliant (Findings F10, F11, F12).", "/capital/projections/1; /reports/capital-adequacy-plan/1; " + PACK + " s.7.0; " + RET + " - 'Capital Planning', 'Forecast Provenance'"),
 ("SCHEDULE I", "SchI-9", "Challenges and Way Forward", "Summarise challenges in improving the risk management framework and controls, and anticipated refinements to the ICAAP.", EVID,
  "Pack s.9.0 prints a four-row challenge register (macro, credit concentration, operational/cyber, data/model) with owners and timelines - code defaults, not ZNBS-confirmed. The return 'Model Risk, Data Quality & BCBS 239' sheet names the specific refinements (independent validation in 2026, close the data-gap register, revisit the model-risk add-on).", "Register should carry ZNBS's own dated actions.", "Tool ready; ZNBS to confirm or replace the register.", PACK + " s.9.0; " + RET + " - 'Challenges & Way Forward', 'Model Risk, Data Quality & BCBS 239'"),
 ("APPENDIX I", "AppI", "Summary of ICAAP (BoZ reporting template)", "Header (institution code, financial year, start/end date); columns Amount, Capital under ICAAP, Pillar 1 Minimum, Stressed Capital, Methodology; rows: CET1, AT1, primary capital, Tier 2, regulatory capital; Pillar 1 credit/market/operational by approach and total (a); risks not covered by Pillar 1 (residual, securitisation, model); Pillar 2 (concentration individual/sectoral/other, IRRBB, liquidity, reputation, strategic, other); ICAAP/Pillar 2 capital (b); overall requirement; current total capital; surplus/(deficit).", PART,
  "All template rows and columns are produced from the bound runs: capital 1,348,811; Pillar 1 340,301 (credit 271,311 standardised, market 0, operational 68,989 BIA); Pillar 2 17,032; overall 459,423; surplus 889,388; stressed capital 1,098,811. Additional rows itemise 'other material risks' (operational RCSA 6,899, cyber 3,450, CSRBB/people/legal/climate nil). Defects: IRRBB methodology reads '|Delta-EVE| worst BCBS scenario' but the amount 2,602 is the NII earnings-at-risk figure (delta EVE on IRRBB run #11 is 167,315); institution code '0021000' is the sample value printed in the gazette template (setting institution_boz_code); start date 2025-01-01 does not match the Apr-Dec 2025 stub period.", "The template's '(c)' is not defined in the gazette; the tool uses Pillar 1 + buffers + Pillar 2 with a nil stress line.", "Partially compliant (Findings F16, F17).", RET + " - sheets 'Appendix I', 'Reconciliation'; Report Centre pack Appendix 1 (Table 23/17); IRRBB run #11 (/irrbb/runs/11)"),
]

FINDINGS = [
 ("F1", "17(1), 17(2), 4(4), 7", "No real Board challenge or approval", "Every approval on the ICAAP is a UAT stand-in: return #1 'board_approved' block = Chief Risk Officer 'For the Board (UAT placeholder - no Board resolution recorded)', signature 'UAT-PLACEHOLDER'; reviewed_by block empty; pack #1 approved by user #4 with reason 'UAT back-end approval ... not a real sign-off'; RAS approved_by NULL. Generated text nevertheless states 'The Board concludes...' (return Executive Summary, pack s.1.0).", "The ICAAP cannot be filed as Board-approved; the Executive Summary asserts a Board conclusion that does not exist.", "Hold the Board meeting on the pack; record the minute reference, signatories and dates through the approval workflow (replacing the UAT entries); obtain the reviewed-by signatures (Director Risk, Director Finance); have the Board approve the RAS, capital management, stress testing and dividend policies.", "ZNBS Board Secretary", "Open"),
 ("F2", "17(3)", "Submission to BoZ not evidenced", "Return #1 status 'submitted' was set by System Administrator on 28 Sep 2026 (approval_audit_logs #3) with submission_reference NULL. Rule 20 requires the ICAAP within 180 days of year-end (README: by 29 Jun 2026 for Dec-2025).", "Filing date and reference cannot be demonstrated from the system.", "ZNBS Compliance to record the actual BoZ submission date and reference (or the agreed extension) on return #1.", "ZNBS Compliance", "Open"),
 ("F3", "3", "Applicability to a building society", "Notice 1198 applies to financial institutions 'where the Bank requests'; no BoZ request or determination is on file in the tool.", "None on the numbers; governs whether the full directive is binding.", "File the BoZ letter (or confirmation that Rule 20 applies to ZNBS) in the documents register.", "ZNBS Compliance", "Open"),
 ("F4", "9", "Pack Appendix 4 overstates the independent review", "_review_of_icaap.blade.php marks Internal Audit, Management, Finance & Audit Committee and Board reviews 'Completed' whenever the pack is Board-approved; pack #1 is 'board_approved' only through the UAT CRO approval, and no review is recorded anywhere (return independent_review NULL).", "The printed pack claims an Internal Audit review that has not happened.", "Drive each layer's status from its own recorded evidence (reviewer, date, findings) - e.g. the return's independent_review block - never from the Board-approval flag.", "Tool - Dupleix", "Open"),
 ("F5", "9", "Independent review of the ICAAP not performed", "No internal or external audit review of the ICAAP is recorded (return independent_review NULL; mrm_validations 0 rows). s.9(4)(a)-(h) areas are unreviewed.", "Non-compliance with s.9 and Schedule I 'Review' item 3.", "Internal Audit to review the Dec-2025 ICAAP against s.9(4)(a)-(h); record reviewer, date, opinion, findings and follow-up in the return's independent-review block.", "ZNBS Internal Audit", "Open"),
 ("F6", "17(1)", "Draft Board resolution and cover letter misstate the stress result", "IcaapReportCentreService prints fixed text: resolution clause 2 'the binding stress produces a regulatory shortfall that requires the recovery-plan actions'; the cover letter carries the same clause and is signed 'Chief Executive Officer' (ZNBS has a Managing Director). The worst stressed CAR is 32.12%, above the 13% effective minimum; the stress capital line is nil.", "The Board would be asked to minute a shortfall that the ICAAP does not show.", "Make clause 2 and the letter conditional on the stress result (as the executive position summary already is); take the signatory title from the profile register.", "Tool - Dupleix", "Open"),
 ("F7", "SchI-6, 11(c)", "Liquidity section contradicts the Executive Summary; placeholders", "Return 'Liquidity & Funding Assessment' (saved narrative) reports LCR 1,988% / NSFR 151.5% as 'the one reported in this return'; the Executive Summary and liquidity run #11 give LCR 2,640.91% / NSFR 131.54% (official statement basis). The same sheet contains 'UAT PLACEHOLDER - to be confirmed by ZNBS' for intra-group arrangements and the Contingency Funding Plan.", "Two different LCR/NSFR figures in one return; CFP (Schedule I 8(g)) unevidenced.", "Rewrite the liquidity narrative on the official run #11 basis (granular figure as comparator only); ZNBS Treasury to supply the Board-approved CFP (triggers, roles, last test date) and confirm no intra-group funding.", "Tool - Dupleix / ZNBS Treasury", "Open"),
 ("F8", "18, SchI-3", "Return omits Schedule I content held only in the pack", "IcaapRegulatoryExcelExporter::worksheets() skips the 'ownership_approval' narrative, so the Review, Challenge, Approval and Embedment section is absent from the return; Schedule I tables (board/committees, policy register, RAS metrics, material risks, five-year financials, loan-book analysis, contingency plan, dividend policy) are only in the Report Centre pack; the return's RAS section refers to an appendix it does not contain.", "Filed alone, the return does not address Schedule I at the minimum s.18 requires.", "Either file the Report Centre pack as the Schedule I document with the return (state this on the Cover), or add the review/embedment narrative and the Schedule I tables to the return exporters.", "Tool - Dupleix", "Open"),
 ("F9", "14(3), SchI-6", "Material-risk table conflicts with Appendix I", "Pack s.5.0 material-risk table (ReportProfileController default copied from the Mar-2025 ICAAP Table 18) shows Business/Strategic 'Pillar 2 judgement add-on (4% of Pillar 1)' and Reputation '(2% of Pillar 1)' as held in ICAAP capital; Dec-2025 Appendix I holds both at nil.", "The pack contradicts itself on which risks are capitalised (about K20m at 6% of Pillar 1).", "Generate the table from the approved Pillar 2 register for the period, or update the profile to the Dec-2025 decisions with the reason each add-on was released.", "Tool - Dupleix / ZNBS Risk", "Open"),
 ("F10", "13(3), SchI-8", "No Board-approved capital plan; target stated three ways", "Capital Adequacy Plan #1 is 'draft' (reviewed_by/approved_by NULL; 'seeded on the demo 3-year projection'). CAR target: RAS 15% (trigger 12%); plan #1 band 13-15%; projection run #1 'stress_derived_band' 30.96-35.96%.", "s.13(3)(i) capital target is ambiguous; s.13(3) Board approval missing.", "Board to set one capital target and approve the capital plan (target, horizon, utilisation, contingency plan); align the projection run's target mode to it.", "ZNBS Finance / Board", "Open"),
 ("F11", "SchI-8", "Capital plan assumptions without a basis", "Projection run #1 records a K250m CET1 issuance in 2027 (planned_actions) with no source; dividends paid are 0 in every projected year although the plan states 60% retained / 40% distributed; the dividend policy (40%) was approved by its creator, user #1.", "Projected 2027-2028 ratios may include an unconfirmed capital injection; Schedule I 2(d)-(e) and item 5 not evidenced.", "ZNBS Finance to confirm whether a capital injection is planned (basis, amount, timing) and the dividend assumption; correct the run and re-approve the dividend policy with a second approver.", "ZNBS Finance", "Open"),
 ("F12", "7(2)(b)", "Capital management policy content is code default", "Policy register dates (ICAAP, Capital Management, Stress Testing policies 'Nov 2025'), contingency triggers and buffer-replenishment text come from ReportProfileController defaults; icaap_report_profile has never been saved.", "Printed as if ZNBS facts.", "ZNBS to confirm or replace each entry in /reports/profile and supply the policies to the documents register.", "ZNBS Risk", "Open"),
 ("F13", "12(2)(b)(vii)", "Per-scenario projection paths ignore the shock after year 0", "Projection run #1 'scenario:N' paths hold each scenario's stressed 2025 Q4 position but every path reverts to the same forecast from 2026 (K1,565,540k, CAR 40.34%), so they do not show capital under each adverse scenario over the horizon.", "Only the single calibrated 'stressed' path is forward-looking.", "Carry each scenario's capital and RWA shock through the forecast periods (CapitalProjectionService::projectPerScenarioPaths) or stop publishing the per-scenario paths.", "Tool - Dupleix", "Open"),
 ("F14", "16", "Model inventory, validation and back-testing", "MRM inventory lists 8 generic models (OLS, AR(1), Monte Carlo, AI Management Action Advisor, etc.) all 'approved' with 0 validations and 0 back-tests; it omits the capital, IFRS 9, stress transmission, liquidity and IRRBB engines the return relies on. No confidence level is assigned to outputs.", "s.16(1)(c),(e) and 16(2) not met; model-risk add-on K2,722k held meanwhile.", "Register the ICAAP engines in /mrm; commission the independent validation promised for 2026; record back-tests and a confidence statement per model.", "ZNBS Risk / Tool - Dupleix", "Open"),
 ("F15", "SchI-7", "Post-management-action capital and Board role in stress testing", "Post-action runs exist for 2 scenarios only (#1 L1 deposit run, #2 C5 NPL), none for the binding scenario; no BoZ-prescribed stress test; scenarios approved by System Administrator, no Board review frequency recorded. Post-action run #1 still leaves NSFR 63.31% and loan-to-deposit 119.04% after actions.", "Schedule I stress item 5 (pre/post capital for all tests) and item 2 not met.", "Run post-action for the binding and every reporting-set scenario (or state why not); record the Board/committee approval of the stress framework and its review frequency; add any BoZ-prescribed scenarios when issued.", "Tool - Dupleix / ZNBS Risk", "Open"),
 ("F16", "AppI", "Appendix I IRRBB methodology label", "Methodology column reads '|Delta-EVE| worst BCBS scenario' (fixed map in IcaapRegulatoryReportService) while the amount K2,602k is the NII earnings-at-risk add-on (governed irrbb_addon_method = nii_earnings); delta EVE is K167,315k.", "Methodology misdescribed in the mandatory BoZ template.", "Take the IRRBB methodology text from the assessment's own basis, as is already done for the six qualitative Pillar 2 rows.", "Tool - Dupleix", "Open"),
 ("F17", "AppI, SchI-4", "Reporting period and institution code", "Institution code '0021000' equals the sample in the gazette template (setting institution_boz_code). Appendix I start date is 2025-01-01 and the pack is labelled 'FY ended 31 December 2025' (months_in_period 12), though ZNBS ran an Apr-Dec 2025 nine-month stub (income statement 2025 id 20, months = 9); the year-end change is not disclosed as a significant development.", "Header identifies the wrong institution/period if not corrected.", "ZNBS to confirm its BoZ institution code; record months = 9 on the Dec-2025 period so the pack and Appendix I header read 'nine months ended 31 December 2025' (start 2025-04-01); add the year-end change to Background.", "ZNBS Finance / Tool - Dupleix", "Open"),
 ("F18", "SchI-4, SchI-5", "Background and governance items missing or unconfirmed", "Only 4 years of actuals shown (2022-2025) though 2021 is loaded; no retail/SME/corporate, geographic or internal-grade analysis; no encumbrance level; no shareholders' willingness statement; ownership table (MoF majority + WCFCB + NAPSA minority) conflicts with the README reading of the AFS (100% GRZ-owned); no directors' experience, independent-director count, terms of reference, delegations or internal-control review evidence.", "Several Schedule I Background and Governance items unanswered or possibly wrong.", "Extend the history to five years (Tool); ZNBS Board Secretary / Finance to supply the ownership, board and committee details and loan-book analyses through /reports/profile.", "ZNBS Board Secretary / Finance; Tool - Dupleix", "Open"),
 ("F19", "SchI-3", "Outsourced ICAAP component not disclosed", "Schedule I Review item 5 requires provider details, risks and mitigation where any ICAAP component is outsourced. The ICAAP is prepared on a system developed by an external party; nothing is disclosed.", "Disclosure gap.", "ZNBS to decide whether the system/support arrangement is outsourcing and, if so, disclose the provider, risks and controls in pack s.2.", "ZNBS Risk", "Open"),
 ("F20", "7(2)(a), SchI-6", "RAS approval, review frequency and depositor-concentration limit", "RAS 26 metrics are 'approved' with approved_by NULL (seeded 28 Sep 2026); no review frequency is stated; Top-20 depositor limit is 40% (trigger 45%) in the RAS, while ALCO/ICAAP documents state 25% (open ZNBS query); current 49.0%.", "Schedule I RA item 1 incomplete; the breach assessment depends on the disputed limit.", "Board to approve the RAS with its review frequency; ZNBS to confirm the depositor limit before the breach commentary is finalised.", "ZNBS Risk / Board", "Open"),
]
