<template><app-layout><template #header><div class="flex items-center justify-between"><div><h2 class="text-xl font-semibold text-gray-800">Time-phased ECL Projection Audit</h2><p class="text-sm text-gray-600">Marginal PD × LGD × EAD, scenario weighting and locked-EIR discounting</p></div><Link :href="route('expected-credit-loss.index')" class="btn">Back to ECL</Link></div></template>
<div class="mx-auto max-w-7xl space-y-5">
 <div v-if="run" class="grid gap-3 md:grid-cols-4"><div class="card"><b>{{ run.contracts_processed }}</b><small>Contracts calculated</small></div><div class="card"><b>{{ run.contracts_unresolved }}</b><small>Unresolved</small></div><div class="card"><b>{{ money(run.undiscounted_ecl) }}</b><small>Undiscounted ECL (MWK)</small></div><div class="card"><b>{{ money(run.discounted_ecl) }}</b><small>Discounted ECL (MWK)</small></div></div>
 <div class="rounded-lg border bg-white p-4 shadow-sm"><form class="flex flex-wrap gap-2" @submit.prevent="filter"><select v-model="form.run_id" class="input"><option v-for="r in runs" :key="r.run_id" :value="r.run_id">{{ r.reporting_period }} · {{ r.run_id.slice(0,8) }}</option></select><select v-model="form.scenario" class="input"><option value="">All scenarios</option><option v-for="s in scenarios" :key="s.scenario_code" :value="s.scenario_code">{{ s.name }} ({{ Number(s.weight)*100 }}%)</option></select><input v-model="form.search" class="input" placeholder="Loan account"><button class="btn">Filter</button></form></div>
 <section class="rounded-lg border bg-white shadow-sm"><div class="border-b p-4"><h3 class="font-semibold">Contract totals</h3></div><div class="overflow-x-auto"><table><thead><tr><th>Contract</th><th>Stage</th><th>Undiscounted</th><th>Discounted</th><th>Horizon</th></tr></thead><tbody><tr v-for="c in contracts" :key="c.contract_id"><td>{{ c.contract_id }}</td><td>{{ c.ifrs9_stage }}</td><td>{{ money(c.undiscounted_ecl) }}</td><td>{{ money(c.weighted_ecl) }}</td><td>{{ Number(c.horizon).toFixed(3) }} years</td></tr></tbody></table></div></section>
 <section class="rounded-lg border bg-white shadow-sm"><div class="border-b p-4"><h3 class="font-semibold">Projection evidence</h3></div><div class="overflow-x-auto"><table><thead><tr><th>Contract</th><th>Scenario</th><th>Period</th><th>Date</th><th>Opening EAD</th><th>Marginal PD</th><th>LGD</th><th>Shortfall</th><th>Factor</th><th>Weighted discounted</th></tr></thead><tbody><tr v-for="r in rows.data" :key="r.id"><td>{{ r.contract_id }}</td><td>{{ r.scenario_code }}</td><td>{{ r.period_index }}</td><td>{{ r.projection_date }}</td><td>{{ money(r.opening_ead) }}</td><td>{{ pct(r.marginal_pd) }}</td><td>{{ pct(r.lgd) }}</td><td>{{ money(r.undiscounted_shortfall) }}</td><td>{{ Number(r.discount_factor).toFixed(6) }}</td><td>{{ money(r.weighted_discounted_shortfall) }}</td></tr></tbody></table></div><div class="flex gap-2 border-t p-4"><button v-for="l in rows.links" :key="l.label" :disabled="!l.url" v-html="l.label" @click="go(l.url)" class="btn disabled:opacity-40"></button></div></section>
</div></app-layout></template>
<script>import AppLayout from '@/Layouts/AppLayout.vue';import {Link,router} from '@inertiajs/vue3';export default{components:{AppLayout,Link},props:{run:Object,rows:Object,contracts:Array,runs:Array,scenarios:Array,filters:Object},data(){return{form:{...this.filters}}},methods:{money(v){return Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})},pct(v){return (Number(v||0)*100).toFixed(4)+'%'},filter(){router.get(this.route('expected-credit-loss.projections'),this.form,{preserveState:false})},go(url){if(url)router.get(url)}}}</script>
<style scoped>.card{@apply rounded-lg border bg-white p-4 shadow-sm}.card b{@apply block text-xl text-gray-900}.card small{@apply mt-1 block uppercase text-gray-500}.input{@apply rounded-md border-gray-300 text-sm}.btn{@apply inline-flex rounded-md border border-gray-300 bg-white px-3 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-50}table{@apply min-w-full}th{@apply whitespace-nowrap bg-maiic-700 px-3 py-3 text-left text-xs uppercase text-white}td{@apply border-t px-3 py-3 text-sm text-gray-700}</style>
