<?php
return [
    'admin' => [
        [
            'name' => 'Dashboard',
            'icon' => 'home',
            'route' => 'dashboard',
            'permissions' => '',
            'dropdown' => false,
            'children' => [],
            'order' => 0,
        ],
        // [
        //     'name' => 'Clients',
        //     'icon' => 'users',
        //     'route' => 'clients.index',
        //     'permissions' => 'clients',
        //     'dropdown' => true,
        //     'children' => [
        //         [
        //             'name' => 'View Names File',
        //             'icon' => 'circle',
        //             'route' => 'clients.index',
        //             'permissions' => 'clients',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 0,
        //         ],
        //         [
        //             'name' => 'Loan Book',
        //             'icon' => 'circle',
        //             'route' => 'loan_applications.loan-book',
        //             'permissions' => 'loan_applications.loan-book',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 1,
        //         ],
        //     ],
        //     'order' => 1,
        // ],
        [
            'name' => 'Clients',
            'icon' => 'users',
            'route' => 'clients.index',
            'permissions' => 'clients',
            'dropdown' => false,
            'children' => [],
            'order' => 1,
        ],
        [
            'name' => 'Loan Book',
            'icon' => 'credit-card',
            'route' => 'loan_applications.loan-book',
            'permissions' => 'loan_applications.loan-book',
            'dropdown' => true,
            'children' => [
                [
                    'name' => 'View Loan Book',
                    'icon' => 'circle',
                    'route' => 'loan_applications.loan-book',
                    'permissions' => 'loan_applications.loan-book',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Expected Credit Loss',
                    'icon' => 'circle',
                    'route' => 'expected-credit-loss.index',
                    'route_check' => 'expected-credit-loss.index',
                    'permissions' => 'loan_applications.loan-book',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
            ],
            'order' => 1,
        ],
        // [
        //     'name' => 'Contracts',
        //     'icon' => 'credit-card',
        //     'route' => 'loan_applications.contracts.index',
        //     'permissions' => 'loan_applications.contracts.index',
        //     'dropdown' => false,
        //     'children' => [],
        //     'order' => 1,
        // ],

        //Loan Portfolios
        [
            'name' => 'Portfolios',
            'icon' => 'database',
            'route' => '',
            'permissions' => '',
            'dropdown' => true,
            'children' => [
                                [
                    'name' => 'Loan Portfolio',
                    'icon' => 'circle',
                    'route' => 'portfolios.index',
                    'permissions' => 'portfolios.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Sector Types',
                    'icon' => 'circle',
                    'route' => 'industry_types.index',
                    'route_check' => 'industry_types.index',
                    'permissions' => 'industry_types.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
            ],
            'order' => 1,
        ],
        //CUSTOM IMPORTS
        [
            'name' => 'Imports',
            'icon' => 'database',
            'route' => 'imports.index',
            'permissions' => 'custom_imports.index',
            'dropdown' => false,
            'children' => [],
            'order' => 1,
        ],

        //FORWARD LOOKING INFORMATION
        [
            'name' => 'Foward Looking Info',
            'icon' => 'chart-bar',
            'permissions' => 'loans.products.index',
            'dropdown' => true,
            'children' => [
                  [
                    'name' => 'Macro Elements',
                    'icon' => 'circle',
                    'route' => 'macro-statistics.index',
                    'permissions' => 'macro-statistics.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Scenarios',
                    'icon' => 'circle',
                    'route' => 'scenarios.profiles',
                    'route_check' => 'scenarios.profiles',
                    'permissions' => 'scenarios.profiles',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
                [
                    'name' => 'Weighted Forecast',
                    'icon' => 'circle',
                    'route' => 'macro-forecast-weighted.index',
                    'route_check' => 'macro-forecast-weighted.index',
                    'permissions' => 'macro-forecast-weighted.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 2,
                ],
            ],
            'order' => 6,
        ],
        [
            'name' => 'Collateral Management',
            'icon' => 'chart-bar',
            'permissions' => 'loans.products.index',
            'dropdown' => true,
            'children' => [
                  [
                    'name' => 'Types',
                    'icon' => 'circle',
                    'route' => 'collateral.types.index',
                    'permissions' => 'collateral.types.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Allocation',
                    'icon' => 'circle',
                    'route' => 'collateral.allocations.index',
                    'route_check' => 'collateral.allocations.index',
                    'permissions' => 'collateral.allocations.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
            ],
            'order' => 6,
        ],


        // [
        //     'name' => 'Loan Applications',
        //     'icon' => 'landmark',
        //     'route' => 'loan_applications.index',
        //     'permissions' => 'loans.applications.index',
        //     'dropdown' => false,
        //     'children' => [],
        //     'order' => 1,
        // ],
        // [
        //     'name' => 'Transition Profiles',
        //     'icon' => 'database',
        //     'route' => '',
        //     'permissions' => 'loans.products.index',
        //     'dropdown' => true,
        //     'children' => [
        //         [
        //             'name' => 'View Transition Profiles',
        //             'icon' => 'circle',
        //             'route' => 'loan_products.index',
        //             'permissions' => 'loans.products.index',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 0,
        //         ],
        //         [
        //             'name' => 'Create Transition Profiles',
        //             'icon' => 'circle',
        //             'route' => 'loan_products.create',
        //             'route_check' => 'loan_products.create',
        //             'permissions' => 'loans.products.create',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 1,
        //         ],
                
        //         [
        //             'name' => 'Manage ECL Variables',
        //             'icon' => 'circle',
        //             'route' => 'loan_products.categories.index',
        //             'route_check' => 'loan_products.categories.*',
        //             'permissions' => 'loans.products.index',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 2,
        //         ],
        //     ],
        //     'order' => 4,
        // ],
        [
            'name' => 'Transition Profiles',
            'icon' => 'database',
            'route' => '',
            'permissions' => 'loans.products.index',
            'dropdown' => true,
            'children' => [
                [
                    'name' => 'View Transition Profiles',
                    'icon' => 'circle',
                    'route' => 'transition-profiles.index',
                    'permissions' => 'loans.products.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Create Transition Profiles',
                    'icon' => 'circle',
                    'route' => 'transition-profiles.create',
                    'route_check' => 'transition-profiles.create',
                    'permissions' => 'transition-profiles.create',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
            ],
            'order' => 4,
        ],

        //Loss Given Default
        [
            'name' => 'Loss Given Default',
            'icon' => 'database',
            'route' => '',
            'permissions' => 'loans.products.index',
            'dropdown' => true,
            'children' => [
            
                 [
                    'name' => 'Monthly LGD',
                    'icon' => 'circle',
                    'route' => 'loss-given-default.index',
                    'permissions' => 'loss-given-default.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Cummulative LGD',
                    'icon' => 'circle',
                    'route' => 'lgd-cummulative.index',
                    'permissions' => 'lgd-cummulative.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],

            ],
            'order' => 4,
        ],
        
        // [
        //     'name' => 'Transition Profile Column',
        //     'icon' => 'check',
        //     'route' => 'scoring_attributes.index',
        //     'route_check' => 'scoring_attributes.*',
        //     'permissions' => 'loans.scoring_attributes.index',
        //     'dropdown' => false,
        //     'children' => [],
        //     'order' => 1,
        // ],
        [
            'name' => 'Transition Matrix',
            'icon' => 'chart-line',
            'route' => '',
            'route_check' => 'transition-matrices.index',
            'permissions' => 'transition-matrices.index',
            'dropdown' => true,
            'children' => [

                 [
                    'name' => 'Monthly Probability',
                    'icon' => 'circle',
                    'route' => 'transition-matrices.index',
                    'permissions' => 'transition-matrices.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'Cummulative Probability',
                    'icon' => 'circle',
                    'route' => 'transition-matrix-cummulative.index',
                    'permissions' => 'transition-matrix-cummulative.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],

            ],
            'order' => 1,
        ],
        // [
        //     'name' => 'Communication',
        //     'icon' => 'mail-bulk',
        //     'route' => '',
        //     'permissions' => 'communication',
        //     'dropdown' => true,
        //     'children' => [
        //         [
        //             'name' => 'View Campaigns',
        //             'icon' => 'circle',
        //             'route' => 'communication.campaigns.index',
        //             'permissions' => 'communication.campaigns.index',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 0,
        //         ],
        //         [
        //             'name' => 'Create Campaign',
        //             'icon' => 'circle',
        //             'route' => 'communication.campaigns.create',
        //             'permissions' => 'communication.campaigns.create',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 1,
        //         ],
        //         [
        //             'name' => 'Manage Templates',
        //             'icon' => 'circle',
        //             'route' => 'communication.templates.index',
        //             'permissions' => 'communication.templates.index',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 2,
        //         ],
        //         [
        //             'name' => ' SMS Gateways',
        //             'icon' => 'circle',
        //             'route' => 'communication.sms_gateways.index',
        //             'permissions' => 'communication.sms_gateways.index',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 3,
        //         ],
        //     ],
        //     'order' => 6,
        // ],
        // Stageing Rules
        [
            'name' => 'Stageing Rules',
            'icon' => 'exclamation-triangle',
            'route' => '',
            'permissions' => 'settings',
            'dropdown' => true,
            'children' => [
                [
                    'name' => 'Quantitative Thresholds',
                    'icon' => 'circle',
                    'route' => 'stageing-rules.index',
                    'permissions' => 'stageing-rules.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 0,
                ],
                [
                    'name' => 'SICR Groups Setup',
                    'icon' => 'circle',
                    'route' => 'sicr-groups.index',
                    'permissions' => 'sicr-groups.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 1,
                ],
                [
                    'name' => 'SICR Alert Items',
                    'icon' => 'circle',
                    'route' => 'sicr-items.index',
                    'permissions' => 'sicr-items.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 2,
                ],
                [
                    'name' => 'SICR Trigger Alerts',
                    'icon' => 'circle',
                    'route' => 'sicr-triggers.index',
                    'permissions' => 'sicr-triggers.index',
                    'dropdown' => false,
                    'children' => [],
                    'order' => 3,
                ],
            ],
            'order' => 8,
        ],

        [
            'name' => 'Reports',
            'icon' => 'chart-bar',
            'route' => 'reports.index',
            'permissions' => 'reports',
            'dropdown' => false,
            'children' => [],
            'order' => 9,
        ],
        [
            'name' => 'Users',
            'icon' => 'users',
            'route' => 'users.index',
            'permissions' => 'users',
            'dropdown' => false,
            'children' => [],
            'order' => 10,
        ],
        // [
        //     'name' => 'Branches',
        //     'icon' => 'building',
        //     'route' => 'branches.index',
        //     'permissions' => 'branches.index',
        //     'dropdown' => false,
        //     'children' => [],
        //     'order' => 11,
        // ],
        // [
        //     'name' => 'Locations',
        //     'icon' => 'map-marker',
        //     'route' => '',
        //     'permissions' => 'locations',
        //     'dropdown' => true,
        //     'children' => [
        //         [
        //             'name' => 'Regions',
        //             'icon' => 'circle',
        //             'route' => 'locations.regions.index',
        //             'permissions' => 'locations.index',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 0,
        //         ],
        //         [
        //             'name' => 'Inkhundla',
        //             'icon' => 'circle',
        //             'route' => 'locations.inkhundla.index',
        //             'permissions' => 'locations.index',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 1,
        //         ],
        //         /*[
        //             'name' => 'Wards',
        //             'icon' => 'circle',
        //             'route' => 'locations.wards.index',
        //             'permissions' => 'locations.index',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 2,
        //         ],
        //         [
        //             'name' => 'Villages',
        //             'icon' => 'circle',
        //             'route' => 'locations.villages.index',
        //             'permissions' => 'locations.index',
        //             'dropdown' => false,
        //             'children' => [],
        //             'order' => 3,
        //         ],*/
        //     ],
        //     'order' => 6,
        // ],
        [
            'name' => 'Settings',
            'icon' => 'cogs',
            'route' => 'settings.index',
            'permissions' => 'settings',
            'dropdown' => false,
            'children' => [],
            'order' => 12,
        ],
    ],
    'member' => [

    ]
];
