<?php

namespace App\Services\Eir;

use Carbon\Carbon;
use InvalidArgumentException;

/**
 * Tier-2 schedule generator — builds an annuity repayment schedule from
 * contract terms when no schedule file has been imported (see
 * docs/EIR_Build.md §4 Phase 2). Output rows are flagged GENERATED by the
 * caller; a generated schedule is an approximation of the contractual
 * promise and is reported as such in the coverage report.
 *
 * Conventions (pending the Phase 0 conventions memo, documented here so
 * they are auditable in the meantime):
 *  - period rate = nominal annual rate / payments_per_year
 *  - during a moratorium, interest capitalises monthly at annual_rate/12
 *    onto the principal (capital + interest holiday, BERL/Anchor pattern)
 *  - instalments are level annuities on the post-moratorium balance
 */
class ScheduleGeneratorService
{
    private const ALLOWED_FREQUENCIES = [1, 2, 4, 6, 12];

    /**
     * @param array $terms {
     *   principal: float           drawn amount (> 0)
     *   annual_rate: float         nominal annual rate as a decimal (0.321)
     *   payments_per_year: int     1 | 2 | 4 | 6 | 12
     *   n_payments: int            instalment count after the moratorium
     *   start_date: string|Carbon  disbursement / origination date
     *   moratorium_months: int     capital+interest holiday (default 0)
     * }
     * @return array {
     *   instalment: float,
     *   capitalised_principal: float,
     *   rows: list<array{due_date: string, principal_due: float, interest_due: float}>
     * }
     */
    public function generate(array $terms): array
    {
        $principal        = (float) ($terms['principal'] ?? 0);
        $annualRate       = (float) ($terms['annual_rate'] ?? 0);
        $paymentsPerYear  = (int) ($terms['payments_per_year'] ?? 12);
        $nPayments        = (int) ($terms['n_payments'] ?? 0);
        $moratoriumMonths = (int) ($terms['moratorium_months'] ?? 0);

        if ($principal <= 0) {
            throw new InvalidArgumentException('principal must be positive');
        }
        if ($annualRate < 0) {
            throw new InvalidArgumentException('annual_rate cannot be negative');
        }
        if (! in_array($paymentsPerYear, self::ALLOWED_FREQUENCIES, true)) {
            throw new InvalidArgumentException('payments_per_year must be one of ' . implode(',', self::ALLOWED_FREQUENCIES));
        }
        if ($nPayments < 1) {
            throw new InvalidArgumentException('n_payments must be at least 1');
        }

        $startDate = Carbon::parse($terms['start_date'] ?? 'today');

        // Capital+interest moratorium: interest accrues monthly and
        // capitalises, so instalments amortise the grown balance.
        $balance = $principal;
        if ($moratoriumMonths > 0 && $annualRate > 0) {
            $balance = $principal * pow(1 + $annualRate / 12, $moratoriumMonths);
        }
        $capitalisedPrincipal = round($balance, 2);
        $balance = $capitalisedPrincipal;

        $periodRate = $annualRate / $paymentsPerYear;
        $instalment = $this->levelInstalment($balance, $periodRate, $nPayments);

        $intervalMonths = intdiv(12, $paymentsPerYear);
        $firstDue = $startDate->copy()->addMonthsNoOverflow($moratoriumMonths + $intervalMonths);

        $rows = [];
        for ($t = 1; $t <= $nPayments; $t++) {
            $interest  = round($balance * $periodRate, 2);
            $principalDue = round($instalment - $interest, 2);

            if ($t === $nPayments) {
                // Close out rounding drift: the final instalment retires the
                // exact remaining balance.
                $principalDue = round($balance, 2);
            }

            $balance = round($balance - $principalDue, 2);

            $rows[] = [
                'due_date'      => $firstDue->copy()
                    ->addMonthsNoOverflow(($t - 1) * $intervalMonths)
                    ->toDateString(),
                'principal_due' => $principalDue,
                'interest_due'  => $interest,
            ];
        }

        return [
            'instalment'            => round($instalment, 2),
            'capitalised_principal' => $capitalisedPrincipal,
            'rows'                  => $rows,
        ];
    }

    /**
     * Level annuity instalment: P·r / (1 − (1+r)^−n); straight-line when
     * the rate is zero.
     */
    private function levelInstalment(float $principal, float $periodRate, int $nPayments): float
    {
        if ($periodRate == 0.0) {
            return $principal / $nPayments;
        }

        return $principal * $periodRate / (1 - pow(1 + $periodRate, -$nPayments));
    }
}
