<template><app-layout>
  <template #header><div><h2 class="font-semibold text-xl text-gray-800">EIR Accounting Rules</h2><p class="mt-1 text-sm text-gray-600">Controlled defaults that suggest whether imported fees and costs are integral to EIR</p></div></template>
  <div class="max-w-6xl mx-auto space-y-6">
    <div class="bg-maiic-50 border border-maiic-200 rounded-lg p-4 text-sm text-maiic-900">Rules make suggestions only. Every imported line remains pending until classified and independently reviewed.</div>
    <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
      <div class="p-6 border-b flex items-center justify-between"><h3 class="text-lg font-semibold">Rule register</h3><button @click="openCreate" class="primary-btn">Create rule</button></div>
      <div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th v-for="h in ['Priority / rule','Matching criteria','Treatment','Approval','Actions']" :key="h" class="th">{{h}}</th></tr></thead><tbody class="divide-y">
        <tr v-for="r in rules" :key="r.id" class="hover:bg-maiic-50"><td class="td"><div class="font-medium">{{r.priority}} · {{r.name}}</div><span :class="r.active?'badge-green':'badge-gray'">{{r.active?'Active':'Inactive'}}</span></td><td class="td text-sm text-gray-600"><div>Type: {{r.fee_type||'any'}}</div><div>Description: {{r.description_contains||'any'}}</div><div>Direction: {{r.cashflow_direction||'either'}} · GL: {{r.gl_account_ref||'any'}}</div></td><td class="td"><span :class="r.proposed_integral?'badge-green':'badge-gray'">{{r.proposed_integral?'Integral':'Non-integral'}}</span><p class="text-xs text-gray-500 mt-1 max-w-xs">{{r.rationale}}</p></td><td class="td"><span :class="r.approved_at?'badge-green':'badge-yellow'">{{r.approved_at?'Approved':'Pending approval'}}</span><div class="text-xs text-gray-500">{{r.approver?.name||''}}</div></td><td class="td whitespace-nowrap"><button @click="edit(r)" class="action">Edit</button><button v-if="!r.approved_at" @click="postRoute('eir-accounting-rules.approve',r.id)" class="action text-maiic-700">Approve</button><button @click="postRoute('eir-accounting-rules.toggle',r.id)" class="action">{{r.active?'Disable':'Enable'}}</button></td></tr>
        <tr v-if="!rules.length"><td colspan="5" class="p-8 text-center text-gray-500">No rules created yet.</td></tr>
      </tbody></table></div>
    </div>
  </div>
  <jet-dialog-modal :show="showModal" max-width="2xl" @close="closeModal"><template #title><div><div class="font-semibold text-gray-900">{{editingId?'Edit accounting rule':'Create accounting rule'}}</div><p class="mt-1 text-sm font-normal text-gray-500">Define the conditions and suggested IFRS 9 treatment.</p></div></template><template #content>
    <div class="rounded-md border border-gray-200 bg-gray-50 p-4 mb-5"><h4 class="text-xs font-semibold uppercase tracking-wide text-gray-500 mb-3">Rule identity</h4><div class="grid grid-cols-1 sm:grid-cols-3 gap-4"><label class="field sm:col-span-2">Rule name<input v-model="form.name" class="form-input mt-1" placeholder="e.g. Direct arrangement fees"></label><label class="field">Priority<input v-model.number="form.priority" type="number" min="1" class="form-input mt-1"></label></div></div>
    <h4 class="text-xs font-semibold uppercase tracking-wide text-gray-500 mb-3">Matching conditions</h4><p class="text-xs text-gray-500 mb-3">Blank conditions match any value.</p><div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <label class="field">Fee/cost type<select v-model="form.fee_type" class="form-input mt-1"><option value="">Any type</option><option v-for="t in feeTypes" :key="t" :value="t">{{t}}</option></select></label><label class="field">Description contains<input v-model="form.description_contains" class="form-input mt-1"></label><label class="field">GL account<input v-model="form.gl_account_ref" class="form-input mt-1"></label>
      <label class="field">Cash direction<select v-model="form.cashflow_direction" class="form-input mt-1"><option value="">Either</option><option value="RECEIVED">Received by MAIIC</option><option value="PAID">Paid by MAIIC</option></select></label><label class="field">Proposed treatment<select v-model="form.proposed_integral" class="form-input mt-1"><option :value="true">Integral - include in EIR</option><option :value="false">Non-integral - exclude from EIR</option></select></label>
      <label class="field sm:col-span-2">Accounting rationale<textarea v-model="form.rationale" rows="3" class="form-input mt-1" placeholder="Explain why this treatment is appropriate"></textarea></label><label class="sm:col-span-2 inline-flex items-center text-sm text-gray-700"><input v-model="form.active" type="checkbox" class="rounded border-gray-300 text-maiic-600 mr-2">Make this rule active</label>
    </div><div v-if="Object.keys(errors).length" class="mt-4 rounded-md bg-red-50 border border-red-200 px-3 py-2 text-sm text-red-700">{{Object.values(errors)[0]}}</div>
  </template><template #footer><button @click="closeModal" class="secondary-btn mr-2">Cancel</button><button @click="save" :disabled="processing" class="primary-btn">{{processing?'Saving…':(editingId?'Update rule':'Create rule')}}</button></template></jet-dialog-modal>
  <teleport to="head"><title>EIR Accounting Rules</title></teleport>
</app-layout></template>
<script>
import AppLayout from '@/Layouts/AppLayout.vue'; import JetDialogModal from '@/Jetstream/DialogModal.vue'
const blank=()=>({name:'',fee_type:'',description_contains:'',gl_account_ref:'',cashflow_direction:'',proposed_integral:true,rationale:'',priority:100,active:true})
export default{components:{AppLayout,JetDialogModal},props:{rules:Array,feeTypes:Array,errors:{type:Object,default:()=>({})}},data:()=>({showModal:false,editingId:null,processing:false,form:blank()}),methods:{reset(){this.editingId=null;this.form=blank()},openCreate(){this.reset();this.showModal=true},closeModal(){if(!this.processing){this.showModal=false;this.reset()}},edit(r){this.editingId=r.id;this.form={name:r.name,fee_type:r.fee_type||'',description_contains:r.description_contains||'',gl_account_ref:r.gl_account_ref||'',cashflow_direction:r.cashflow_direction||'',proposed_integral:!!r.proposed_integral,rationale:r.rationale,priority:r.priority,active:!!r.active};this.showModal=true},save(){this.processing=true;const done=()=>this.processing=false,close=()=>{this.showModal=false;this.reset()};this.editingId?this.$inertia.put(this.route('eir-accounting-rules.update',this.editingId),this.form,{onFinish:done,onSuccess:close}):this.$inertia.post(this.route('eir-accounting-rules.store'),this.form,{onFinish:done,onSuccess:close})},postRoute(n,id){this.$inertia.post(this.route(n,id),{})}}}
</script>
<style scoped>.field{@apply block text-sm font-medium text-gray-700}.form-input{@apply block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-maiic-500}.primary-btn{@apply inline-flex px-4 py-2 rounded-md text-sm font-medium text-white bg-gradient-to-r from-maiic-600 to-maiic-600 disabled:opacity-50}.secondary-btn{@apply inline-flex px-4 py-2 rounded-md text-sm font-medium bg-white border border-gray-300 text-gray-700}.th{@apply px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase}.td{@apply px-4 py-3 align-top}.badge-green{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-maiic-100 text-maiic-800}.badge-yellow{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-amber-100 text-amber-800}.badge-gray{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-gray-100 text-gray-700}.action{@apply mr-3 text-sm text-maiic-700 hover:underline}</style>
