<template>
  <app-layout>
    <template #header><div><div class="mb-1 flex items-center gap-2 text-xs text-gray-500"><span>EIR &amp; Revenue Recognition</span><span>/</span><span class="font-medium text-maiic-700">Fee Classification</span></div><h2 class="font-semibold text-xl text-gray-800">Fee and Cost Classification</h2><p class="mt-1 text-sm text-gray-600">Classify imported fee and cost lines, then have someone else review them before the EIR is calculated</p></div></template>
    <template #actions><button @click="rematch" class="secondary-btn whitespace-nowrap">Re-apply rules to pending lines</button></template>
    <div class="w-full space-y-6">
      <KpiRow :cards="cards" />
      <div class="maiic-filterbar"><div class="grid grid-cols-1 md:grid-cols-4 gap-3 items-end"><label class="block"><span class="maiic-flabel">Contract or account</span><input v-model="filter.contract_id" class="form-input" placeholder="Part of the number" @keyup.enter="applyFilters"></label><label class="block"><span class="maiic-flabel">Status</span><select v-model="filter.status" class="form-input"><option value="">All statuses</option><option v-for="s in statuses" :key="s" :value="s">{{ statusLabel(s) }}</option></select></label><label class="block"><span class="maiic-flabel">Fee or cost type</span><select v-model="filter.fee_type" class="form-input capitalize"><option value="">All types</option><option v-for="t in feeTypes" :key="t" :value="t">{{ t }}</option></select></label><div><button @click="applyFilters" class="primary-btn justify-center w-full md:w-auto">Apply filters</button></div></div></div>
      <div class="rounded-lg border border-gray-200 bg-white p-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div class="text-sm">
          <div class="font-medium text-gray-900">Accounting rulebook</div>
          <div class="text-xs text-gray-600">
            {{ ruleCoverage.approved_rules }} approved rule(s)<span v-if="ruleCoverage.draft_rules">, {{ ruleCoverage.draft_rules }} awaiting approval</span>.
            <template v-if="ruleCoverage.pending">
              {{ ruleCoverage.pending_matched }} of {{ ruleCoverage.pending }} pending line(s) carry a matched rule.
            </template>
            <template v-else>No pending lines.</template>
          </div>
          <div v-if="unmatchedPending > 0" class="mt-1 text-xs text-amber-700">
            {{ unmatchedPending }} pending line(s) have no matched rule. Re-apply after approving rules, or classify them manually.
          </div>
        </div>
      </div>

      <div v-if="selected.length" class="bg-maiic-50 border border-maiic-200 rounded-lg p-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div class="font-medium text-maiic-900">{{selected.length}} selected line(s)<span v-if="selectedMatched < selected.length" class="ml-2 text-xs font-normal text-amber-700">{{ selected.length - selectedMatched }} without a matched rule</span></div><div class="flex flex-wrap gap-2"><button @click="openClassify('rule')" class="primary-btn" :disabled="selectedMatched===0">Classify using each line's rule</button><button @click="openClassify('manual')" class="secondary-btn">Classify manually</button><button @click="showReviewModal=true" class="secondary-btn">Review/approve</button></div></div>
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200">
        <thead><tr><th class="th"><input type="checkbox" :checked="allSelected" @change="toggleAll"></th><th class="th">Contract / reference</th><th class="th">Fee or cost</th><th class="th text-right">Amount</th><th class="th">Rule suggestion</th><th class="th">Decision</th><th class="th">Status</th></tr></thead>
        <tbody class="divide-y divide-gray-200"><tr v-for="fee in fees.data" :key="fee.id" class="hover:bg-maiic-50"><td class="td"><input type="checkbox" :value="fee.id" v-model="selected" :disabled="fee.classification_status==='REVIEWED'"></td><td class="td"><div class="font-medium text-gray-900">{{ fee.contract_id }}</div><div class="text-xs text-gray-500">{{ fee.source_reference || fee.external_transaction_id || 'No source reference' }}</div></td><td class="td"><div class="capitalize font-medium">{{ fee.fee_type }}</div><div class="text-xs text-gray-500">{{ fee.description || 'No description' }} · {{ fee.cashflow_direction || 'direction pending' }}</div></td><td class="td font-medium text-right tabular-nums whitespace-nowrap">{{ money(fee.amount) }} <span class="text-xs text-gray-500">{{ fee.currency }}</span></td><td class="td"><template v-if="fee.suggested_rule"><div class="text-sm">{{ fee.suggested_rule.name }}</div><span :class="fee.suggested_integral ? 'badge-green':'badge-gray'">{{ fee.suggested_integral ? 'Integral':'Non-integral' }}</span></template><span v-else class="text-xs text-gray-400">No matching rule</span></td><td class="td"><span v-if="fee.integral!==null" :class="fee.integral ? 'badge-green':'badge-gray'">{{ fee.integral ? 'Integral':'Non-integral' }}</span><div class="text-xs text-gray-500 mt-1 max-w-xs">{{ fee.classification_reason }}</div></td><td class="td"><span :class="statusClass(fee.classification_status)">{{ statusLabel(fee.classification_status) }}</span></td></tr><tr v-if="!fees.data.length"><td colspan="7" class="p-10 text-center text-sm text-gray-500"><template v-if="filter.status || filter.fee_type || filter.contract_id">No fee or cost lines match these filters. Clear a filter to see more.</template><template v-else>No fee or cost lines have been imported yet. Load fees through <Link :href="route('eir-intake.index')" class="font-semibold text-maiic-700 underline">EIR Data Intake</Link>, then classify them here.</template></td></tr></tbody>
      </table></div><div v-if="fees.links && fees.links.length > 3" class="px-4 pb-4 border-t"><Pagination :links="fees.links" /></div></div>
    </div>
    <jet-dialog-modal :show="showClassifyModal" @close="closeClassify"><template #title>{{ decision.mode==='rule' ? 'Classify by rule' : 'Classify manually' }}, {{selected.length}} line(s)</template><template #content><div class="space-y-4"><div v-if="decision.mode==='rule'" class="rounded-md border border-maiic-200 bg-maiic-50 p-3 text-sm text-maiic-900">Each line takes the treatment from its own matched rule, so a mixed selection resolves correctly in one action.<div class="mt-1 text-xs">{{ selectedMatched }} of {{ selected.length }} selected line(s) will be classified.<span v-if="selected.length - selectedMatched > 0"> The remaining {{ selected.length - selectedMatched }} have no matched rule and will be skipped, not guessed.</span></div></div><label v-if="decision.mode==='manual'" class="block text-sm font-medium text-gray-700">EIR treatment<select v-model="decision.integral" class="form-input mt-1"><option :value="null">Choose treatment</option><option :value="true">Integral - include in EIR</option><option :value="false">Non-integral - exclude</option></select></label><label v-if="decision.mode==='manual'" class="block text-sm font-medium text-gray-700">Accounting rule<select v-model="decision.accounting_rule_id" class="form-input mt-1"><option value="">No linked rule</option><option v-for="r in rules" :key="r.id" :value="r.id">{{r.name}}</option></select></label><label class="block text-sm font-medium text-gray-700">Accounting reason<textarea v-model="decision.reason" rows="3" class="form-input mt-1" :placeholder="decision.mode==='rule' ? 'e.g. Applied the approved rulebook following the December fee delivery.' : ''"></textarea></label><p v-if="localError||Object.keys(errors).length" class="text-sm text-red-700">{{localError||Object.values(errors)[0]}}</p></div></template><template #footer><button @click="closeClassify" class="secondary-btn mr-2">Cancel</button><button @click="classify" class="primary-btn">Save classification</button></template></jet-dialog-modal>
    <jet-dialog-modal :show="showReviewModal" @close="showReviewModal=false"><template #title>Approve classifications</template><template #content><p class="text-sm text-gray-700">Approve the classifications for <strong>{{selected.length}}</strong> selected line(s)? You cannot review decisions that you classified yourself.</p><p v-if="Object.keys(errors).length" class="mt-3 text-sm text-red-700">{{Object.values(errors)[0]}}</p></template><template #footer><button @click="showReviewModal=false" class="secondary-btn mr-2">Cancel</button><button @click="review" class="primary-btn">Approve classifications</button></template></jet-dialog-modal>
    <teleport to="head"><title>EIR Fee Classification</title></teleport>
  </app-layout>
</template>
<script>
import AppLayout from '@/Layouts/AppLayout.vue'
import JetDialogModal from '@/Jetstream/DialogModal.vue'
import { Link } from '@inertiajs/vue3'
import KpiRow from '@/Components/Maiic/KpiRow.vue'
export default { components:{AppLayout,JetDialogModal,Link,KpiRow}, props:{fees:Object,rules:Array,filters:Object,summary:Object,ruleCoverage:{type:Object,default:()=>({pending:0,pending_matched:0,approved_rules:0,draft_rules:0})},errors:{type:Object,default:()=>({})}}, data(){return{showClassifyModal:false,showReviewModal:false,statuses:['PENDING','CLASSIFIED','REVIEWED','REJECTED'],feeTypes:['arrangement','legal','appraisal','default','levy','other'],selected:[],filter:{status:this.filters.status||'',fee_type:this.filters.fee_type||'',contract_id:this.filters.contract_id||''},decision:{mode:'manual',integral:null,accounting_rule_id:'',reason:''},localError:null}},computed:{cards(){return this.statuses.map(st=>({label:this.statusLabel(st)+' lines',value:Number(this.summary[st]?.line_count||0),sub:this.money(this.summary[st]?.total_amount||0),accent:st==='REVIEWED'?'#15803d':st==='REJECTED'?'#dc2626':st==='PENDING'?'#d97706':'#0f766e'}))},allSelected(){return this.fees.data.length>0&&this.fees.data.filter(f=>f.classification_status!=='REVIEWED').every(f=>this.selected.includes(f.id))},unmatchedPending(){return Math.max(0,(this.ruleCoverage.pending||0)-(this.ruleCoverage.pending_matched||0))},selectedMatched(){return this.fees.data.filter(f=>this.selected.includes(f.id)&&f.suggested_rule_id!==null&&f.suggested_rule_id!==undefined).length}},methods:{statusLabel(st){return {PENDING:'Pending',CLASSIFIED:'Classified',REVIEWED:'Reviewed',REJECTED:'Rejected'}[st]||st},money(v){return Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})},statusClass(s){return s==='REVIEWED'?'badge-green':s==='CLASSIFIED'?'badge-blue':s==='REJECTED'?'badge-red':'badge-yellow'},toggleAll(e){this.selected=e.target.checked?this.fees.data.filter(f=>f.classification_status!=='REVIEWED').map(f=>f.id):[]},applyFilters(){this.$inertia.get(this.route('eir-fee-classification.index'),this.filter,{preserveState:true})},go(url){if(url)this.$inertia.get(url,{}, {preserveState:true})},rematch(){this.$inertia.post(this.route('eir-fee-classification.rematch'),{},{preserveScroll:true})},openClassify(mode){this.decision.mode=mode;this.localError=null;this.showClassifyModal=true},closeClassify(){this.showClassifyModal=false;this.localError=null},classify(){this.localError=null;if(!this.decision.reason.trim()){this.localError='Enter the accounting reason.';return}if(this.decision.mode==='manual'&&this.decision.integral===null){this.localError='Choose a treatment.';return}this.$inertia.post(this.route('eir-fee-classification.classify'),{fee_ids:this.selected,...this.decision},{onSuccess:()=>{this.showClassifyModal=false;this.selected=[];this.decision={mode:'manual',integral:null,accounting_rule_id:'',reason:''}}})},review(){this.$inertia.post(this.route('eir-fee-classification.review'),{fee_ids:this.selected},{onSuccess:()=>{this.showReviewModal=false;this.selected=[]}})}}
}
</script>
<style scoped>
.form-input{@apply block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-maiic-500}
</style>
