<template>
  <app-layout>
    <template #header><div><h2 class="font-semibold text-xl text-gray-800">EIR Fee & Cost Classification</h2><p class="mt-1 text-sm text-gray-600">Classify imported lines, then independently review them before EIR calculation</p></div></template>
    <div class="max-w-7xl mx-auto space-y-6">
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4"><div v-for="s in statuses" :key="s" class="bg-white border border-gray-200 shadow-sm rounded-lg p-4"><div class="text-2xl font-bold text-gray-800">{{ summary[s]?.line_count || 0 }}</div><div class="text-xs text-gray-500">{{ s }} lines</div><div class="text-sm text-gray-700 mt-1">{{ money(summary[s]?.total_amount || 0) }}</div></div></div>
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4"><div class="grid grid-cols-1 md:grid-cols-4 gap-3"><input v-model="filter.contract_id" class="form-input" placeholder="Contract/account"><select v-model="filter.status" class="form-input"><option value="">All statuses</option><option v-for="s in statuses" :key="s">{{ s }}</option></select><select v-model="filter.fee_type" class="form-input"><option value="">All types</option><option v-for="t in feeTypes" :key="t">{{ t }}</option></select><button @click="applyFilters" class="primary-btn justify-center">Apply filters</button></div></div>
      <div v-if="selected.length" class="bg-indigo-50 border border-indigo-200 rounded-lg p-4 flex items-center justify-between"><div class="font-medium text-indigo-900">{{selected.length}} selected line(s)</div><div class="flex gap-2"><button @click="showClassifyModal=true" class="primary-btn">Classify</button><button @click="showReviewModal=true" class="secondary-btn">Review/approve</button></div></div>
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50"><tr><th class="th"><input type="checkbox" :checked="allSelected" @change="toggleAll"></th><th class="th">Contract / reference</th><th class="th">Fee or cost</th><th class="th">Amount</th><th class="th">Rule suggestion</th><th class="th">Decision</th><th class="th">Status</th></tr></thead>
        <tbody class="divide-y divide-gray-200"><tr v-for="fee in fees.data" :key="fee.id" class="hover:bg-indigo-50"><td class="td"><input type="checkbox" :value="fee.id" v-model="selected" :disabled="fee.classification_status==='REVIEWED'"></td><td class="td"><div class="font-medium text-gray-900">{{ fee.contract_id }}</div><div class="text-xs text-gray-500">{{ fee.source_reference || fee.external_transaction_id || 'No source reference' }}</div></td><td class="td"><div class="capitalize font-medium">{{ fee.fee_type }}</div><div class="text-xs text-gray-500">{{ fee.description || 'No description' }} · {{ fee.cashflow_direction || 'direction pending' }}</div></td><td class="td font-medium">{{ money(fee.amount) }} <span class="text-xs text-gray-500">{{ fee.currency }}</span></td><td class="td"><template v-if="fee.suggested_rule"><div class="text-sm">{{ fee.suggested_rule.name }}</div><span :class="fee.suggested_integral ? 'badge-green':'badge-gray'">{{ fee.suggested_integral ? 'Integral':'Non-integral' }}</span></template><span v-else class="text-xs text-gray-400">No matching rule</span></td><td class="td"><span v-if="fee.integral!==null" :class="fee.integral ? 'badge-green':'badge-gray'">{{ fee.integral ? 'Integral':'Non-integral' }}</span><div class="text-xs text-gray-500 mt-1 max-w-xs">{{ fee.classification_reason }}</div></td><td class="td"><span :class="statusClass(fee.classification_status)">{{ fee.classification_status }}</span></td></tr><tr v-if="!fees.data.length"><td colspan="7" class="p-8 text-center text-gray-500">No fee or cost lines match these filters.</td></tr></tbody>
      </table></div><div class="p-4 flex flex-wrap gap-2 border-t"><button v-for="link in fees.links" :key="link.label" v-html="link.label" :disabled="!link.url" @click="go(link.url)" class="px-3 py-1 border rounded text-sm disabled:opacity-40" :class="link.active?'bg-maiic-600 text-white':'bg-white text-gray-700'"></button></div></div>
    </div>
    <jet-dialog-modal :show="showClassifyModal" @close="closeClassify"><template #title>Classify {{selected.length}} fee/cost line(s)</template><template #content><div class="space-y-4"><label class="block text-sm font-medium text-gray-700">EIR treatment<select v-model="decision.integral" class="form-input mt-1"><option :value="null">Choose treatment</option><option :value="true">Integral — include in EIR</option><option :value="false">Non-integral — exclude</option></select></label><label class="block text-sm font-medium text-gray-700">Accounting rule<select v-model="decision.accounting_rule_id" class="form-input mt-1"><option value="">No linked rule</option><option v-for="r in rules" :key="r.id" :value="r.id">{{r.name}}</option></select></label><label class="block text-sm font-medium text-gray-700">Accounting reason<textarea v-model="decision.reason" rows="3" class="form-input mt-1"></textarea></label><p v-if="localError||Object.keys(errors).length" class="text-sm text-red-700">{{localError||Object.values(errors)[0]}}</p></div></template><template #footer><button @click="closeClassify" class="secondary-btn mr-2">Cancel</button><button @click="classify" class="primary-btn">Save classification</button></template></jet-dialog-modal>
    <jet-dialog-modal :show="showReviewModal" @close="showReviewModal=false"><template #title>Approve classifications</template><template #content><p class="text-sm text-gray-700">Approve the classifications for <strong>{{selected.length}}</strong> selected line(s)? You cannot review decisions that you classified yourself.</p><p v-if="Object.keys(errors).length" class="mt-3 text-sm text-red-700">{{Object.values(errors)[0]}}</p></template><template #footer><button @click="showReviewModal=false" class="secondary-btn mr-2">Cancel</button><button @click="review" class="primary-btn">Approve classifications</button></template></jet-dialog-modal>
    <teleport to="head"><title>EIR Fee Classification</title></teleport>
  </app-layout>
</template>
<script>
import AppLayout from '@/Layouts/AppLayout.vue'
import JetDialogModal from '@/Jetstream/DialogModal.vue'
export default { components:{AppLayout,JetDialogModal}, props:{fees:Object,rules:Array,filters:Object,summary:Object,errors:{type:Object,default:()=>({})}}, data(){return{showClassifyModal:false,showReviewModal:false,statuses:['PENDING','CLASSIFIED','REVIEWED','REJECTED'],feeTypes:['arrangement','legal','appraisal','default','levy','other'],selected:[],filter:{status:this.filters.status||'',fee_type:this.filters.fee_type||'',contract_id:this.filters.contract_id||''},decision:{integral:null,accounting_rule_id:'',reason:''},localError:null}},computed:{allSelected(){return this.fees.data.length>0&&this.fees.data.filter(f=>f.classification_status!=='REVIEWED').every(f=>this.selected.includes(f.id))}},methods:{money(v){return Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})},statusClass(s){return s==='REVIEWED'?'badge-green':s==='CLASSIFIED'?'badge-blue':s==='REJECTED'?'badge-red':'badge-yellow'},toggleAll(e){this.selected=e.target.checked?this.fees.data.filter(f=>f.classification_status!=='REVIEWED').map(f=>f.id):[]},applyFilters(){this.$inertia.get(this.route('eir-fee-classification.index'),this.filter,{preserveState:true})},go(url){if(url)this.$inertia.get(url,{}, {preserveState:true})},closeClassify(){this.showClassifyModal=false;this.localError=null},classify(){this.localError=null;if(this.decision.integral===null||!this.decision.reason.trim()){this.localError='Choose a treatment and enter the accounting reason.';return}this.$inertia.post(this.route('eir-fee-classification.classify'),{fee_ids:this.selected,...this.decision},{onSuccess:()=>{this.showClassifyModal=false;this.selected=[];this.decision={integral:null,accounting_rule_id:'',reason:''}}})},review(){this.$inertia.post(this.route('eir-fee-classification.review'),{fee_ids:this.selected},{onSuccess:()=>{this.showReviewModal=false;this.selected=[]}})}}
}
</script>
<style scoped>
.form-input{@apply block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-maiic-500}.primary-btn{@apply inline-flex px-4 py-2 rounded-md text-sm font-medium text-white bg-gradient-to-r from-maiic-600 to-teal-600 hover:from-maiic-700 hover:to-teal-700}.secondary-btn{@apply inline-flex px-4 py-2 rounded-md text-sm font-medium bg-white border border-gray-300 text-gray-700}.th{@apply px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider}.td{@apply px-4 py-3 align-top text-sm}.badge-green{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-green-100 text-green-800}.badge-blue{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-blue-100 text-blue-800}.badge-yellow{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-yellow-100 text-yellow-800}.badge-red{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-red-100 text-red-800}.badge-gray{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-gray-100 text-gray-700}
</style>
