<template>
  <app-layout>
    <template #header><div><div class="mb-1 flex items-center gap-2 text-xs text-gray-500"><Link :href="route('eir-data.index')" class="hover:text-maiic-700">EIR Data</Link><span>/</span><span class="font-medium text-maiic-700">Fee Classification</span></div><h2 class="font-semibold text-xl text-gray-800">EIR Fee & Cost Classification</h2><p class="mt-1 text-sm text-gray-600">Classify imported lines, then independently review them before EIR calculation</p></div></template>
    <div class="max-w-7xl mx-auto space-y-6">
      <div class="grid grid-cols-2 md:grid-cols-4 gap-4"><div v-for="s in statuses" :key="s" class="bg-white border border-gray-200 shadow-sm rounded-lg p-4"><div class="text-2xl font-bold text-gray-800">{{ summary[s]?.line_count || 0 }}</div><div class="text-xs text-gray-500">{{ s }} lines</div><div class="text-sm text-gray-700 mt-1">{{ money(summary[s]?.total_amount || 0) }}</div></div></div>
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4"><div class="grid grid-cols-1 md:grid-cols-4 gap-3"><input v-model="filter.contract_id" class="form-input" placeholder="Contract/account"><select v-model="filter.status" class="form-input"><option value="">All statuses</option><option v-for="s in statuses" :key="s">{{ s }}</option></select><select v-model="filter.fee_type" class="form-input"><option value="">All types</option><option v-for="t in feeTypes" :key="t">{{ t }}</option></select><button @click="applyFilters" class="primary-btn justify-center">Apply filters</button></div></div>
      <div class="rounded-lg border border-gray-200 bg-white p-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
        <div class="text-sm">
          <div class="font-medium text-gray-900">Accounting rulebook</div>
          <div class="text-xs text-gray-600">
            {{ ruleCoverage.approved_rules }} approved rule(s)<span v-if="ruleCoverage.draft_rules">, {{ ruleCoverage.draft_rules }} awaiting approval</span>.
            <template v-if="ruleCoverage.pending">
              {{ ruleCoverage.pending_matched }} of {{ ruleCoverage.pending }} pending line(s) carry a matched rule.
            </template>
            <template v-else>No pending lines.</template>
          </div>
          <div v-if="unmatchedPending > 0" class="mt-1 text-xs text-amber-700">
            {{ unmatchedPending }} pending line(s) have no matched rule. Re-apply after approving rules, or classify them manually.
          </div>
        </div>
        <button @click="rematch" class="secondary-btn whitespace-nowrap">Re-apply rules to pending lines</button>
      </div>

      <div v-if="selected.length" class="bg-maiic-50 border border-maiic-200 rounded-lg p-4 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div class="font-medium text-maiic-900">{{selected.length}} selected line(s)<span v-if="selectedMatched < selected.length" class="ml-2 text-xs font-normal text-amber-700">{{ selected.length - selectedMatched }} without a matched rule</span></div><div class="flex flex-wrap gap-2"><button @click="openClassify('rule')" class="primary-btn" :disabled="selectedMatched===0">Classify using each line's rule</button><button @click="openClassify('manual')" class="secondary-btn">Classify manually</button><button @click="showReviewModal=true" class="secondary-btn">Review/approve</button></div></div>
      <div class="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200">
        <thead><tr><th class="th"><input type="checkbox" :checked="allSelected" @change="toggleAll"></th><th class="th">Contract / reference</th><th class="th">Fee or cost</th><th class="th">Amount</th><th class="th">Rule suggestion</th><th class="th">Decision</th><th class="th">Status</th></tr></thead>
        <tbody class="divide-y divide-gray-200"><tr v-for="fee in fees.data" :key="fee.id" class="hover:bg-maiic-50"><td class="td"><input type="checkbox" :value="fee.id" v-model="selected" :disabled="fee.classification_status==='REVIEWED'"></td><td class="td"><div class="font-medium text-gray-900">{{ fee.contract_id }}</div><div class="text-xs text-gray-500">{{ fee.source_reference || fee.external_transaction_id || 'No source reference' }}</div></td><td class="td"><div class="capitalize font-medium">{{ fee.fee_type }}</div><div class="text-xs text-gray-500">{{ fee.description || 'No description' }} · {{ fee.cashflow_direction || 'direction pending' }}</div></td><td class="td font-medium">{{ money(fee.amount) }} <span class="text-xs text-gray-500">{{ fee.currency }}</span></td><td class="td"><template v-if="fee.suggested_rule"><div class="text-sm">{{ fee.suggested_rule.name }}</div><span :class="fee.suggested_integral ? 'badge-green':'badge-gray'">{{ fee.suggested_integral ? 'Integral':'Non-integral' }}</span></template><span v-else class="text-xs text-gray-400">No matching rule</span></td><td class="td"><span v-if="fee.integral!==null" :class="fee.integral ? 'badge-green':'badge-gray'">{{ fee.integral ? 'Integral':'Non-integral' }}</span><div class="text-xs text-gray-500 mt-1 max-w-xs">{{ fee.classification_reason }}</div></td><td class="td"><span :class="statusClass(fee.classification_status)">{{ fee.classification_status }}</span></td></tr><tr v-if="!fees.data.length"><td colspan="7" class="p-8 text-center text-gray-500">No fee or cost lines match these filters.</td></tr></tbody>
      </table></div><div class="p-4 flex flex-wrap gap-2 border-t"><button v-for="link in fees.links" :key="link.label" v-html="link.label" :disabled="!link.url" @click="go(link.url)" class="px-3 py-1 border rounded text-sm disabled:opacity-40" :class="link.active?'bg-maiic-600 text-white':'bg-white text-gray-700'"></button></div></div>
    </div>
    <jet-dialog-modal :show="showClassifyModal" @close="closeClassify"><template #title>{{ decision.mode==='rule' ? 'Classify by rule' : 'Classify manually' }} — {{selected.length}} line(s)</template><template #content><div class="space-y-4"><div v-if="decision.mode==='rule'" class="rounded-md border border-maiic-200 bg-maiic-50 p-3 text-sm text-maiic-900">Each line takes the treatment from its own matched rule, so a mixed selection resolves correctly in one action.<div class="mt-1 text-xs">{{ selectedMatched }} of {{ selected.length }} selected line(s) will be classified.<span v-if="selected.length - selectedMatched > 0"> The remaining {{ selected.length - selectedMatched }} have no matched rule and will be skipped, not guessed.</span></div></div><label v-if="decision.mode==='manual'" class="block text-sm font-medium text-gray-700">EIR treatment<select v-model="decision.integral" class="form-input mt-1"><option :value="null">Choose treatment</option><option :value="true">Integral - include in EIR</option><option :value="false">Non-integral - exclude</option></select></label><label v-if="decision.mode==='manual'" class="block text-sm font-medium text-gray-700">Accounting rule<select v-model="decision.accounting_rule_id" class="form-input mt-1"><option value="">No linked rule</option><option v-for="r in rules" :key="r.id" :value="r.id">{{r.name}}</option></select></label><label class="block text-sm font-medium text-gray-700">Accounting reason<textarea v-model="decision.reason" rows="3" class="form-input mt-1" :placeholder="decision.mode==='rule' ? 'e.g. Applied the approved rulebook following the December fee delivery.' : ''"></textarea></label><p v-if="localError||Object.keys(errors).length" class="text-sm text-red-700">{{localError||Object.values(errors)[0]}}</p></div></template><template #footer><button @click="closeClassify" class="secondary-btn mr-2">Cancel</button><button @click="classify" class="primary-btn">Save classification</button></template></jet-dialog-modal>
    <jet-dialog-modal :show="showReviewModal" @close="showReviewModal=false"><template #title>Approve classifications</template><template #content><p class="text-sm text-gray-700">Approve the classifications for <strong>{{selected.length}}</strong> selected line(s)? You cannot review decisions that you classified yourself.</p><p v-if="Object.keys(errors).length" class="mt-3 text-sm text-red-700">{{Object.values(errors)[0]}}</p></template><template #footer><button @click="showReviewModal=false" class="secondary-btn mr-2">Cancel</button><button @click="review" class="primary-btn">Approve classifications</button></template></jet-dialog-modal>
    <teleport to="head"><title>EIR Fee Classification</title></teleport>
  </app-layout>
</template>
<script>
import AppLayout from '@/Layouts/AppLayout.vue'
import JetDialogModal from '@/Jetstream/DialogModal.vue'
import { Link } from '@inertiajs/vue3'
export default { components:{AppLayout,JetDialogModal,Link}, props:{fees:Object,rules:Array,filters:Object,summary:Object,ruleCoverage:{type:Object,default:()=>({pending:0,pending_matched:0,approved_rules:0,draft_rules:0})},errors:{type:Object,default:()=>({})}}, data(){return{showClassifyModal:false,showReviewModal:false,statuses:['PENDING','CLASSIFIED','REVIEWED','REJECTED'],feeTypes:['arrangement','legal','appraisal','default','levy','other'],selected:[],filter:{status:this.filters.status||'',fee_type:this.filters.fee_type||'',contract_id:this.filters.contract_id||''},decision:{mode:'manual',integral:null,accounting_rule_id:'',reason:''},localError:null}},computed:{allSelected(){return this.fees.data.length>0&&this.fees.data.filter(f=>f.classification_status!=='REVIEWED').every(f=>this.selected.includes(f.id))},unmatchedPending(){return Math.max(0,(this.ruleCoverage.pending||0)-(this.ruleCoverage.pending_matched||0))},selectedMatched(){return this.fees.data.filter(f=>this.selected.includes(f.id)&&f.suggested_rule_id!==null&&f.suggested_rule_id!==undefined).length}},methods:{money(v){return Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})},statusClass(s){return s==='REVIEWED'?'badge-green':s==='CLASSIFIED'?'badge-blue':s==='REJECTED'?'badge-red':'badge-yellow'},toggleAll(e){this.selected=e.target.checked?this.fees.data.filter(f=>f.classification_status!=='REVIEWED').map(f=>f.id):[]},applyFilters(){this.$inertia.get(this.route('eir-fee-classification.index'),this.filter,{preserveState:true})},go(url){if(url)this.$inertia.get(url,{}, {preserveState:true})},rematch(){this.$inertia.post(this.route('eir-fee-classification.rematch'),{},{preserveScroll:true})},openClassify(mode){this.decision.mode=mode;this.localError=null;this.showClassifyModal=true},closeClassify(){this.showClassifyModal=false;this.localError=null},classify(){this.localError=null;if(!this.decision.reason.trim()){this.localError='Enter the accounting reason.';return}if(this.decision.mode==='manual'&&this.decision.integral===null){this.localError='Choose a treatment.';return}this.$inertia.post(this.route('eir-fee-classification.classify'),{fee_ids:this.selected,...this.decision},{onSuccess:()=>{this.showClassifyModal=false;this.selected=[];this.decision={mode:'manual',integral:null,accounting_rule_id:'',reason:''}}})},review(){this.$inertia.post(this.route('eir-fee-classification.review'),{fee_ids:this.selected},{onSuccess:()=>{this.showReviewModal=false;this.selected=[]}})}}
}
</script>
<style scoped>
.form-input{@apply block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-maiic-500}.primary-btn{@apply inline-flex px-4 py-2 rounded-md text-sm font-medium text-white bg-gradient-to-r from-maiic-600 to-maiic-600 hover:from-maiic-700 hover:to-maiic-700}.secondary-btn{@apply inline-flex px-4 py-2 rounded-md text-sm font-medium bg-white border border-gray-300 text-gray-700}.th{@apply px-4 py-3 bg-maiic-700 text-left text-[11px] font-bold text-white uppercase tracking-wider whitespace-nowrap}.td{@apply px-4 py-2.5 align-top text-sm border-t border-gray-100}tbody tr:nth-child(even){@apply bg-gray-50}tbody tr:hover{@apply bg-maiic-50/60}.badge-green{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-maiic-100 text-maiic-800}.badge-blue{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-maiic-100 text-maiic-800}.badge-yellow{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-amber-100 text-amber-800}.badge-red{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-red-100 text-red-800}.badge-gray{@apply inline-flex px-2 py-0.5 rounded-full text-xs bg-gray-100 text-gray-700}
</style>
